begin;

-- migration-check: allow-destructive
-- Reviewed rollback posture: this migration is expand-only.  The marker is
-- required because PostgreSQL TRUNCATE triggers/privileges are mentioned in
-- the append-only guard; rollback never drops rows or disables the guards.

-- Native TRNM receipt snapshots are immutable evidence.  The legacy
-- trnm_economic_receipts row remains as a compatibility seed/projection; every
-- settlement attempt is recorded in this append-only event stream so a
-- recoverable hold can be retried without rewriting the original evidence.

create table if not exists public.trnm_economic_receipt_events_v1 (
    event_id bigint generated by default as identity primary key,
    intent_id text not null
        references public.trnm_economic_intents(intent_id),
    event_sequence bigint not null,
    intent_hash text not null,
    receipt_id text not null,
    protocol_version text not null,
    idempotency_scope text not null,
    idempotency_key text not null,
    progression_class text not null,
    status text not null,
    amount_credits bigint not null default 0,
    receipt_json jsonb not null,
    receipt_hash text not null,
    event_kind text not null default 'initial',
    finalized_at timestamptz not null,
    created_at timestamptz not null default now(),
    constraint trnm_receipt_events_sequence_v1
        check (event_sequence > 0),
    constraint trnm_receipt_events_intent_hash_v1
        check (intent_hash ~ '^[0-9a-f]{64}$'),
    constraint trnm_receipt_events_receipt_hash_v1
        check (receipt_hash ~ '^[0-9a-f]{64}$'),
    constraint trnm_receipt_events_progression_v1
        check (progression_class in (
            'progression_allowed', 'recoverable_hold', 'terminal_skip', 'hard_fail'
        )),
    constraint trnm_receipt_events_status_v1
        check (length(btrim(status)) between 1 and 128),
    constraint trnm_receipt_events_amount_v1
        check (amount_credits >= 0),
    constraint trnm_receipt_events_event_kind_v1
        check (event_kind in ('initial', 'recoverable_hold_retry', 'progression')),
    constraint trnm_receipt_events_json_v1
        check (jsonb_typeof(receipt_json) = 'object'),
    constraint trnm_receipt_events_identity_v1
        unique (intent_id, event_sequence)
);

create index if not exists idx_trnm_receipt_events_latest_v1
    on public.trnm_economic_receipt_events_v1(intent_id, event_sequence desc, event_id desc);

create index if not exists idx_trnm_receipt_events_finalized_v1
    on public.trnm_economic_receipt_events_v1(finalized_at desc, event_id desc);

-- An interrupted rollout may have created the event table before the amount column was added.
-- Make the upgrade path explicit and backfill only from immutable intent/evidence bytes; unknown
-- legacy amounts become zero and therefore fail closed at value-bearing consumers.
alter table public.trnm_economic_receipt_events_v1
    add column if not exists amount_credits bigint;

-- The amount/evidence backfill is the only compatibility repair in this
-- expand migration.  A previous attempt may already have installed the
-- append-only mutation guards before it was interrupted.  Drop those guards
-- inside this transaction while repairing legacy rows; if the transaction is
-- interrupted PostgreSQL rolls the drops back, and a retry starts safely.
drop trigger if exists trg_cex_reject_trnm_economic_receipt_event_mutation_v1
    on public.trnm_economic_receipt_events_v1;
drop trigger if exists trg_cex_reject_trnm_economic_receipt_event_truncate_v1
    on public.trnm_economic_receipt_events_v1;

-- Never let malformed/overflowing legacy JSON abort the migration.  Invalid
-- evidence is normalized to NULL and then to zero, which remains explicitly
-- non-progressing at every value-bearing consumer.  The helper is removed at
-- the end of this migration; it is not part of the runtime API.
create or replace function public.cex_trnm_nonnegative_bigint_or_null_v1(raw_value text)
returns bigint
language plpgsql
set search_path = pg_catalog, public
as $function$
declare
    parsed_value bigint;
begin
    if raw_value is null or btrim(raw_value) = '' then
        return null;
    end if;
    begin
        parsed_value := raw_value::bigint;
    exception when others then
        return null;
    end;
    -- A negative amount is invalid evidence, not a legitimate zero.  Return
    -- NULL so the caller can fall through to the immutable intent (or the
    -- already-stored non-negative projection) instead of clobbering a real
    -- positive amount with a synthetic zero.
    if parsed_value < 0 then
        return null;
    end if;
    return parsed_value;
end
$function$;

-- Normalize legacy JSON identity fields only where they are absent.  Conflicting
-- identity/status/hash fields are deliberately preserved so the validation
-- trigger (and the explicit post-backfill check below) can reject tampered or
-- forked evidence instead of silently rewriting it.  Amount evidence is the
-- one intentional compatibility repair: when immutable intent.amount_credits
-- is valid, it is canonicalized below so an old, stale amount cannot authorize
-- a different value; new writes still reject any mismatch.
create or replace function public.cex_trnm_normalize_receipt_json_v1(
    raw_value jsonb,
    expected_intent_id text,
    expected_receipt_id text,
    expected_protocol_version text,
    expected_status text,
    expected_progression_class text,
    expected_payload_hash text,
    resolved_amount bigint
)
returns jsonb
language plpgsql
immutable
set search_path = pg_catalog, public
as $function$
declare
    normalized jsonb;
begin
    normalized := case
        when jsonb_typeof(raw_value) = 'object' then raw_value
        else '{}'::jsonb
    end;
    if normalized ->> 'intent_id' is null then
        normalized := jsonb_set(normalized, '{intent_id}', to_jsonb(expected_intent_id), true);
    end if;
    if normalized ->> 'receipt_id' is null then
        normalized := jsonb_set(normalized, '{receipt_id}', to_jsonb(expected_receipt_id), true);
    end if;
    if normalized ->> 'protocol_version' is null then
        normalized := jsonb_set(normalized, '{protocol_version}', to_jsonb(expected_protocol_version), true);
    end if;
    if normalized ->> 'status' is null then
        normalized := jsonb_set(normalized, '{status}', to_jsonb(expected_status), true);
    end if;
    if normalized ->> 'progression_class' is null then
        normalized := jsonb_set(normalized, '{progression_class}', to_jsonb(expected_progression_class), true);
    end if;
    -- `jsonb_typeof(NULL)` is SQL NULL, so a plain `<> 'object'` would
    -- silently skip both a missing and an explicit JSON null evidence node.
    -- Treat every non-object (including SQL NULL) as an empty evidence object
    -- before filling the immutable bindings.
    if jsonb_typeof(normalized -> 'evidence') is distinct from 'object' then
        normalized := jsonb_set(normalized, '{evidence}', '{}'::jsonb, true);
    end if;
    normalized := jsonb_set(
        normalized,
        '{evidence,amount_credits}',
        to_jsonb(coalesce(resolved_amount, 0)),
        true
    );
    if normalized #>> '{evidence,payload_hash}' is null then
        normalized := jsonb_set(
            normalized,
            '{evidence,payload_hash}',
            to_jsonb(expected_payload_hash),
            true
        );
    end if;
    return normalized;
end
$function$;

-- Reconcile every partially-created row, not only NULL/negative columns.  A
-- valid non-negative amount in the immutable intent is the authority; an
-- invalid/negative intent amount is fail-closed to zero.  Only when the intent
-- omits amount_credits (the audit-only CompleteContract shape) may receipt
-- evidence, then the already-stored non-negative projection, provide a
-- compatibility fallback.  This matters for an interrupted rollout where the
-- new column acquired its default `0` before the evidence backfill ran:
-- blindly trusting that zero would erase a real amount on the next retry.
with resolved_amounts as (
    select e.event_id,
           e.intent_id,
           e.receipt_id,
           e.protocol_version,
           e.status,
           e.progression_class,
           e.receipt_json,
           i.payload_hash,
           public.cex_trnm_nonnegative_bigint_or_null_v1(
               e.receipt_json #>> '{evidence,amount_credits}'
           ) as evidence_amount,
           public.cex_trnm_nonnegative_bigint_or_null_v1(
               i.intent_json ->> 'amount_credits'
           ) as intent_amount,
           coalesce(
               (i.intent_json ? 'amount_credits')
                   and jsonb_typeof(i.intent_json -> 'amount_credits') <> 'null',
               false
           ) as intent_amount_present,
           coalesce(
               (i.intent_json ? 'amount_credits')
                   and jsonb_typeof(i.intent_json -> 'amount_credits') = 'number'
                   and public.cex_trnm_nonnegative_bigint_or_null_v1(
                       i.intent_json ->> 'amount_credits'
                   ) is not null,
               false
           ) as intent_amount_valid,
           case when e.amount_credits >= 0 then e.amount_credits end as stored_amount
      from public.trnm_economic_receipt_events_v1 e
      join public.trnm_economic_intents i using (intent_id)
), chosen_amounts as (
    select *,
           case
               when intent_amount_valid then intent_amount
               when intent_amount_present then 0
               else coalesce(evidence_amount, stored_amount, 0)
           end as amount_credits
      from resolved_amounts
), normalized_rows as (
    select chosen_amounts.*,
           public.cex_trnm_normalize_receipt_json_v1(
               receipt_json,
               intent_id,
               receipt_id,
               protocol_version,
               status,
               progression_class,
               payload_hash,
               amount_credits
           ) as normalized_receipt_json
      from chosen_amounts
)
-- This pass runs after resolving immutable intent/evidence precedence, so an
-- existing default zero can never overwrite a valid immutable intent value.
update public.trnm_economic_receipt_events_v1 e
   set amount_credits = normalized_rows.amount_credits,
       receipt_json = normalized_rows.normalized_receipt_json,
       receipt_hash = encode(
           digest(normalized_rows.normalized_receipt_json::text, 'sha256'),
           'hex'
       )
  from normalized_rows
  join chosen_amounts chosen
    on chosen.event_id = normalized_rows.event_id
 where e.event_id = normalized_rows.event_id
   and (
       e.amount_credits is distinct from chosen.amount_credits
       or e.receipt_json is distinct from normalized_rows.normalized_receipt_json
       or e.receipt_hash is distinct from encode(
           digest(normalized_rows.normalized_receipt_json::text, 'sha256'),
           'hex'
       )
   );
alter table public.trnm_economic_receipt_events_v1
    alter column amount_credits set default 0,
    alter column amount_credits set not null;
do $constraint$
begin
    if not exists (
        select 1
          from pg_catalog.pg_constraint c
          join pg_catalog.pg_class t on t.oid = c.conrelid
          join pg_catalog.pg_namespace n on n.oid = t.relnamespace
         where n.nspname = 'public'
           and t.relname = 'trnm_economic_receipt_events_v1'
           and c.conname = 'trnm_receipt_events_amount_v1'
    ) then
        alter table public.trnm_economic_receipt_events_v1
            add constraint trnm_receipt_events_amount_v1 check (amount_credits >= 0);
    end if;
end
$constraint$;

create or replace function public.cex_validate_trnm_economic_receipt_event_v1()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $function$
declare
    intent_row record;
    expected_sequence bigint;
    previous_progression text;
    previous_receipt_id text;
    seed_receipt_id text;
    immutable_amount bigint;
    immutable_amount_present boolean := false;
    immutable_amount_invalid boolean := false;
begin
    select protocol_version, idempotency_scope, idempotency_key, payload_hash,
           intent_json -> 'amount_credits' as amount_json
      into intent_row
      from public.trnm_economic_intents
     where intent_id = new.intent_id;
    if not found then
        raise exception 'TRNM receipt event intent binding does not exist';
    end if;
    if new.intent_hash is distinct from intent_row.payload_hash
       or new.protocol_version is distinct from intent_row.protocol_version
       or new.idempotency_scope is distinct from intent_row.idempotency_scope
       or new.idempotency_key is distinct from intent_row.idempotency_key then
        raise exception 'TRNM receipt event immutable intent binding mismatch';
    end if;

    -- `amount_credits` is optional only for audit-only intents.  When the key
    -- is present, it is immutable authority: it must be a JSON integer and
    -- non-negative.  Malformed/negative intent amounts deliberately collapse
    -- to zero so a corrupt intent can never authorize value-bearing evidence.
    if intent_row.amount_json is not null
       and jsonb_typeof(intent_row.amount_json) <> 'null' then
        immutable_amount_present := true;
        if jsonb_typeof(intent_row.amount_json) <> 'number'
           or (intent_row.amount_json #>> '{}') !~ '^-?[0-9]+$' then
            immutable_amount_invalid := true;
        else
            begin
                immutable_amount := (intent_row.amount_json #>> '{}')::bigint;
            exception when others then
                immutable_amount_invalid := true;
            end;
            if immutable_amount is null or immutable_amount < 0 then
                immutable_amount_invalid := true;
            end if;
        end if;
    end if;
    if immutable_amount_invalid then
        if new.amount_credits is distinct from 0 then
            raise exception 'TRNM receipt event amount is not authorized by an invalid immutable intent amount';
        end if;
    elsif immutable_amount_present
          and new.amount_credits is distinct from immutable_amount then
        raise exception 'TRNM receipt event amount does not match immutable intent amount';
    end if;

    select coalesce(max(event_sequence), 0) + 1
      into expected_sequence
      from public.trnm_economic_receipt_events_v1
     where intent_id = new.intent_id;
    if new.event_sequence is distinct from expected_sequence then
        raise exception 'TRNM receipt event sequence must append the next contiguous snapshot';
    end if;
    if expected_sequence = 1 then
        -- A compatibility seed may already exist when an interrupted 0086
        -- rollout is resumed.  Never let a first event fork that identity.
        select receipt_id
          into seed_receipt_id
          from public.trnm_economic_receipts
         where intent_id = new.intent_id;
        if seed_receipt_id is not null
           and new.receipt_id is distinct from seed_receipt_id then
            raise exception 'TRNM receipt event receipt_id conflicts with immutable compatibility seed';
        end if;
    end if;
    select progression_class, receipt_id
      into previous_progression, previous_receipt_id
      from public.trnm_economic_receipt_events_v1
     where intent_id = new.intent_id
     order by event_sequence desc, event_id desc
     limit 1;
    if expected_sequence > 1
       and new.receipt_id is distinct from previous_receipt_id then
        raise exception 'TRNM receipt event receipt_id must remain stable for an intent';
    end if;
    -- A recoverable hold is the only non-terminal state that may receive a
    -- later snapshot.  Once an attempt has reached an allowed, skipped, or
    -- hard-fail class, accepting another event would permit a terminal result
    -- to be rewritten by a subsequent hold/retry.
    if expected_sequence > 1
       and previous_progression is distinct from 'recoverable_hold' then
        raise exception 'TRNM terminal receipt event cannot append after final progression';
    end if;
    if expected_sequence = 1 and new.event_kind <> 'initial' then
        raise exception 'TRNM receipt event sequence one must be initial';
    end if;
    if expected_sequence > 1 and new.event_kind = 'initial' then
        raise exception 'TRNM receipt retry event cannot be initial';
    end if;
    if previous_progression = 'recoverable_hold'
       and new.event_kind <> 'recoverable_hold_retry' then
        raise exception 'TRNM recoverable-hold retry must be marked as a retry event';
    end if;
    if previous_progression is distinct from 'recoverable_hold'
       and new.event_kind = 'recoverable_hold_retry' then
        raise exception 'TRNM receipt retry event requires a recoverable-hold predecessor';
    end if;
    if new.receipt_json ->> 'intent_id' is distinct from new.intent_id
       or new.receipt_json ->> 'receipt_id' is distinct from new.receipt_id
       or new.receipt_json ->> 'protocol_version' is distinct from new.protocol_version
       or new.receipt_json #>> '{evidence,payload_hash}' is distinct from new.intent_hash
       or jsonb_typeof(new.receipt_json #> '{evidence,amount_credits}') is distinct from 'number'
       or (new.receipt_json #>> '{evidence,amount_credits}') !~ '^-?[0-9]+$'
       or coalesce(new.receipt_json #> '{evidence,amount_credits}', 'null'::jsonb)
          is distinct from to_jsonb(new.amount_credits)
       or new.receipt_json ->> 'status' is distinct from new.status
       or new.receipt_json ->> 'progression_class' is distinct from new.progression_class then
        raise exception 'TRNM receipt event JSON binding mismatch';
    end if;
    if (case
            when new.status in (
                'reserved', 'settled', 'reopened_settled', 'consumed', 'refunded',
                'seller_chargeback_reserved', 'seller_chargeback_consumed',
                'approved_release', 'duplicate'
            ) then 'progression_allowed'
            when new.status in (
                'skipped_zero_price', 'skipped_zero_reward', 'skipped_zero_seller_net'
            ) then 'terminal_skip'
            when new.status in (
                'held_review', 'skipped_missing_room', 'failed_network', 'failed_identity',
                'failed_ledger', 'seller_chargeback_reserve_failed',
                'seller_chargeback_failed', 'rejected_refund_failed',
                'cancelled_refund_failed'
            ) then 'recoverable_hold'
            when new.status in (
                'failed_bad_response', 'skipped_missing_account',
                'skipped_missing_ledger_token', 'missing_account', 'missing_ledger_token'
            ) then 'hard_fail'
            else null
        end) is distinct from new.progression_class then
        raise exception 'TRNM receipt status/progression mapping mismatch';
    end if;
    if new.receipt_hash is distinct from
       encode(digest(new.receipt_json::text, 'sha256'), 'hex') then
        raise exception 'TRNM receipt event hash mismatch';
    end if;
    return new;
end
$function$;

drop trigger if exists trg_cex_validate_trnm_economic_receipt_event_v1
    on public.trnm_economic_receipt_events_v1;
create trigger trg_cex_validate_trnm_economic_receipt_event_v1
before insert on public.trnm_economic_receipt_events_v1
for each row
execute function public.cex_validate_trnm_economic_receipt_event_v1();

-- Backfill the first immutable snapshot for rows written by 0027.  Resolve
-- the amount with the same immutable-intent-first precedence used above before
-- constructing the JSON/hash.  The NOT-EXISTS guard makes the expand migration
-- safe to replay on a partially upgraded database.
with legacy_rows as (
    select r.intent_id,
           r.receipt_id,
           r.protocol_version,
           r.idempotency_scope,
           r.idempotency_key,
           r.progression_class,
           r.status,
           r.receipt_json,
           r.finalized_at,
           r.created_at,
           i.payload_hash,
           public.cex_trnm_nonnegative_bigint_or_null_v1(
               r.receipt_json #>> '{evidence,amount_credits}'
           ) as evidence_amount,
           public.cex_trnm_nonnegative_bigint_or_null_v1(
               i.intent_json ->> 'amount_credits'
           ) as intent_amount,
           coalesce(
               (i.intent_json ? 'amount_credits')
                   and jsonb_typeof(i.intent_json -> 'amount_credits') <> 'null',
               false
           ) as intent_amount_present,
           coalesce(
               (i.intent_json ? 'amount_credits')
                   and jsonb_typeof(i.intent_json -> 'amount_credits') = 'number'
                   and public.cex_trnm_nonnegative_bigint_or_null_v1(
                       i.intent_json ->> 'amount_credits'
                   ) is not null,
               false
           ) as intent_amount_valid
      from public.trnm_economic_receipts r
      join public.trnm_economic_intents i using (intent_id)
), resolved_rows as (
    select legacy_rows.*,
           case
               when intent_amount_valid then intent_amount
               when intent_amount_present then 0
               else coalesce(evidence_amount, 0)
           end as resolved_amount
      from legacy_rows
), normalized_rows as (
    select resolved_rows.*,
           public.cex_trnm_normalize_receipt_json_v1(
               receipt_json,
               intent_id,
               receipt_id,
               protocol_version,
               status,
               progression_class,
               payload_hash,
               resolved_amount
           ) as normalized_receipt_json
      from resolved_rows
)
insert into public.trnm_economic_receipt_events_v1 (
    intent_id, event_sequence, intent_hash, receipt_id, protocol_version,
    idempotency_scope, idempotency_key, progression_class, status, amount_credits, receipt_json,
    receipt_hash, event_kind, finalized_at, created_at
)
select normalized_rows.intent_id,
       1,
       normalized_rows.payload_hash,
       normalized_rows.receipt_id,
       normalized_rows.protocol_version,
       normalized_rows.idempotency_scope,
       normalized_rows.idempotency_key,
       normalized_rows.progression_class,
       normalized_rows.status,
       normalized_rows.resolved_amount,
       normalized_rows.normalized_receipt_json,
       encode(digest(normalized_rows.normalized_receipt_json::text, 'sha256'), 'hex'),
       'initial',
       normalized_rows.finalized_at,
       normalized_rows.created_at
  from normalized_rows
 where not exists (
           select 1
             from public.trnm_economic_receipt_events_v1 e
            where e.intent_id = normalized_rows.intent_id
             and e.event_sequence = 1
       );

-- Existing rows were present before the INSERT trigger was installed.  Verify
-- them explicitly after compatibility normalization so a conflicting legacy
-- field cannot survive merely because it was not missing.
do $validation$
begin
    if exists (
        select 1
          from public.trnm_economic_receipt_events_v1 e
          join public.trnm_economic_intents i using (intent_id)
         where e.receipt_json ->> 'intent_id' is distinct from e.intent_id
            or e.receipt_json ->> 'receipt_id' is distinct from e.receipt_id
            or e.receipt_json ->> 'protocol_version' is distinct from e.protocol_version
            or e.receipt_json ->> 'status' is distinct from e.status
            or e.receipt_json ->> 'progression_class' is distinct from e.progression_class
            or e.receipt_json #>> '{evidence,payload_hash}' is distinct from e.intent_hash
            or jsonb_typeof(e.receipt_json #> '{evidence,amount_credits}') is distinct from 'number'
            or (e.receipt_json #>> '{evidence,amount_credits}') !~ '^-?[0-9]+$'
            or coalesce(e.receipt_json #> '{evidence,amount_credits}', 'null'::jsonb)
               is distinct from to_jsonb(e.amount_credits)
            or e.receipt_hash is distinct from
               encode(digest(e.receipt_json::text, 'sha256'), 'hex')
            or (
                (i.intent_json ? 'amount_credits')
                and jsonb_typeof(i.intent_json -> 'amount_credits') <> 'null'
                and (
                    (
                        jsonb_typeof(i.intent_json -> 'amount_credits') = 'number'
                        and (i.intent_json ->> 'amount_credits') ~ '^-?[0-9]+$'
                        and public.cex_trnm_nonnegative_bigint_or_null_v1(
                            i.intent_json ->> 'amount_credits'
                        ) is not null
                        and e.amount_credits is distinct from
                            public.cex_trnm_nonnegative_bigint_or_null_v1(
                                i.intent_json ->> 'amount_credits'
                            )
                    )
                    or (
                        (
                            jsonb_typeof(i.intent_json -> 'amount_credits') <> 'number'
                            or (i.intent_json ->> 'amount_credits') !~ '^-?[0-9]+$'
                            or public.cex_trnm_nonnegative_bigint_or_null_v1(
                                i.intent_json ->> 'amount_credits'
                            ) is null
                        )
                        and e.amount_credits is distinct from 0
                    )
                )
            )
    ) then
        raise exception 'TRNM legacy receipt evidence failed compatibility validation';
    end if;
    if exists (
        select 1
          from public.trnm_economic_receipt_events_v1 e
          join public.trnm_economic_receipts r using (intent_id)
         where e.event_sequence = 1
           and e.receipt_id is distinct from r.receipt_id
    ) then
        raise exception 'TRNM native receipt history/seed receipt_id conflict';
    end if;
    if exists (
        select 1
          from public.trnm_economic_receipt_events_v1
         group by intent_id
        having count(distinct receipt_id) > 1
    ) then
        raise exception 'TRNM native receipt history contains multiple receipt_ids for one intent';
    end if;
end
$validation$;

create or replace function public.cex_reject_trnm_economic_receipt_event_mutation_v1()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $function$
begin
    raise exception using
        errcode = '55000',
        message = 'TRNM native receipt event evidence is append-only';
end;
$function$;

drop trigger if exists trg_cex_reject_trnm_economic_receipt_event_mutation_v1
    on public.trnm_economic_receipt_events_v1;
create trigger trg_cex_reject_trnm_economic_receipt_event_mutation_v1
before update or delete on public.trnm_economic_receipt_events_v1
for each statement
execute function public.cex_reject_trnm_economic_receipt_event_mutation_v1();

drop trigger if exists trg_cex_reject_trnm_economic_receipt_event_truncate_v1
    on public.trnm_economic_receipt_events_v1;
create trigger trg_cex_reject_trnm_economic_receipt_event_truncate_v1
before truncate on public.trnm_economic_receipt_events_v1
for each statement
execute function public.cex_reject_trnm_economic_receipt_event_mutation_v1();

drop function public.cex_trnm_normalize_receipt_json_v1(
    jsonb, text, text, text, text, text, text, bigint
);
drop function public.cex_trnm_nonnegative_bigint_or_null_v1(text);

alter table public.trnm_economic_receipt_events_v1
    enable always trigger trg_cex_validate_trnm_economic_receipt_event_v1;
alter table public.trnm_economic_receipt_events_v1
    enable always trigger trg_cex_reject_trnm_economic_receipt_event_mutation_v1;
alter table public.trnm_economic_receipt_events_v1
    enable always trigger trg_cex_reject_trnm_economic_receipt_event_truncate_v1;

revoke update, delete, truncate
    on table public.trnm_economic_receipt_events_v1
    from public;

-- 0027's one-row table is retained only as an immutable compatibility seed.
-- New repository writes use INSERT ... ON CONFLICT DO NOTHING; retries are
-- represented by the event stream above rather than an UPDATE to this row.
create or replace function public.cex_reject_trnm_economic_receipt_mutation_v1()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $function$
begin
    raise exception using
        errcode = '55000',
        message = 'TRNM native receipt seed evidence is append-only';
end;
$function$;

drop trigger if exists trg_cex_reject_trnm_economic_receipt_mutation_v1
    on public.trnm_economic_receipts;
create trigger trg_cex_reject_trnm_economic_receipt_mutation_v1
before update or delete on public.trnm_economic_receipts
for each statement
execute function public.cex_reject_trnm_economic_receipt_mutation_v1();

drop trigger if exists trg_cex_reject_trnm_economic_receipt_truncate_v1
    on public.trnm_economic_receipts;
create trigger trg_cex_reject_trnm_economic_receipt_truncate_v1
before truncate on public.trnm_economic_receipts
for each statement
execute function public.cex_reject_trnm_economic_receipt_mutation_v1();

alter table public.trnm_economic_receipts
    enable always trigger trg_cex_reject_trnm_economic_receipt_mutation_v1;
alter table public.trnm_economic_receipts
    enable always trigger trg_cex_reject_trnm_economic_receipt_truncate_v1;

revoke update, delete, truncate
    on table public.trnm_economic_receipts
    from public;

comment on table public.trnm_economic_receipt_events_v1 is
    'Append-only native TRNM receipt snapshots; recoverable holds append a later event';
comment on table public.trnm_economic_receipts is
    'Immutable 0027 compatibility seed; latest native receipt is read from the event stream';

commit;
