begin;

-- migration-check: allow-destructive
-- Reviewed rollback posture: this migration is expand-only.  The only
-- destructive-looking tokens are the append-only UPDATE/DELETE/TRUNCATE
-- guards; rollback never removes receipt evidence or disables those guards.

-- The 0026 projection tables intentionally retain one row per receipt_id for
-- compatibility with existing API/read models.  A retry can, however, move a
-- receipt from recoverable_hold to a final class without changing receipt_id.
-- These event tables preserve every distinct immutable snapshot in sequence;
-- the projection row is never used as a mutable history record.

create table if not exists public.league_term_exchange_receipt_events_v1 (
    event_id bigint generated by default as identity primary key,
    receipt_id text not null,
    event_sequence bigint not null,
    event_kind text not null default 'initial',
    previous_receipt_hash text,
    protocol_version text not null,
    intent_id text not null,
    term_id text not null,
    backend_id text not null,
    backend_kind text not null,
    status text not null,
    progression_class text not null,
    settlement_reference text,
    ledger_entry_id text,
    reason text,
    amount_credits bigint,
    finalized_at timestamptz not null,
    receipt_json jsonb not null,
    receipt_hash text not null,
    created_at timestamptz not null default now(),
    constraint league_term_exchange_receipt_events_sequence_v1
        check (event_sequence > 0),
    constraint league_term_exchange_receipt_events_previous_hash_v1
        check (previous_receipt_hash is null or previous_receipt_hash ~ '^sha256:[0-9a-f]{64}$'),
    constraint league_term_exchange_receipt_events_hash_v1
        check (receipt_hash ~ '^sha256:[0-9a-f]{64}$'),
    constraint league_term_exchange_receipt_events_status_v1
        check (length(btrim(status)) between 1 and 128),
    constraint league_term_exchange_receipt_events_progression_v1
        check (progression_class in (
            'progression_allowed', 'recoverable_hold', 'terminal_skip', 'hard_fail'
        )),
    constraint league_term_exchange_receipt_events_kind_v1
        check (event_kind in ('initial', 'backfill', 'hold', 'final', 'transition')),
    constraint league_term_exchange_receipt_events_amount_v1
        check (amount_credits is null or amount_credits >= 0),
    constraint league_term_exchange_receipt_events_json_v1
        check (jsonb_typeof(receipt_json) = 'object'),
    constraint league_term_exchange_receipt_events_identity_v1
        unique (receipt_id, event_sequence)
);

create table if not exists public.world_term_exchange_receipt_events_v1 (
    event_id bigint generated by default as identity primary key,
    receipt_id text not null,
    event_sequence bigint not null,
    event_kind text not null default 'initial',
    previous_receipt_hash text,
    protocol_version text not null,
    intent_id text not null,
    term_id text not null,
    backend_id text not null,
    backend_kind text not null,
    status text not null,
    progression_class text not null,
    settlement_reference text,
    ledger_entry_id text,
    reason text,
    amount_credits bigint,
    finalized_at timestamptz not null,
    receipt_json jsonb not null,
    receipt_hash text not null,
    created_at timestamptz not null default now(),
    constraint world_term_exchange_receipt_events_sequence_v1
        check (event_sequence > 0),
    constraint world_term_exchange_receipt_events_previous_hash_v1
        check (previous_receipt_hash is null or previous_receipt_hash ~ '^sha256:[0-9a-f]{64}$'),
    constraint world_term_exchange_receipt_events_hash_v1
        check (receipt_hash ~ '^sha256:[0-9a-f]{64}$'),
    constraint world_term_exchange_receipt_events_status_v1
        check (length(btrim(status)) between 1 and 128),
    constraint world_term_exchange_receipt_events_progression_v1
        check (progression_class in (
            'progression_allowed', 'recoverable_hold', 'terminal_skip', 'hard_fail'
        )),
    constraint world_term_exchange_receipt_events_kind_v1
        check (event_kind in ('initial', 'backfill', 'hold', 'final', 'transition')),
    constraint world_term_exchange_receipt_events_amount_v1
        check (amount_credits is null or amount_credits >= 0),
    constraint world_term_exchange_receipt_events_json_v1
        check (jsonb_typeof(receipt_json) = 'object'),
    constraint world_term_exchange_receipt_events_identity_v1
        unique (receipt_id, event_sequence)
);

create index if not exists idx_league_term_exchange_receipt_events_latest_v1
    on public.league_term_exchange_receipt_events_v1(receipt_id, event_sequence desc, event_id desc);
create index if not exists idx_league_term_exchange_receipt_events_finalized_v1
    on public.league_term_exchange_receipt_events_v1(finalized_at desc, event_id desc);
create index if not exists idx_league_term_exchange_receipt_events_intent_v1
    on public.league_term_exchange_receipt_events_v1(intent_id, finalized_at desc, event_id desc);
create unique index if not exists uq_league_term_exchange_receipt_events_initial_intent_v1
    on public.league_term_exchange_receipt_events_v1(intent_id)
    where event_sequence = 1;

create index if not exists idx_world_term_exchange_receipt_events_latest_v1
    on public.world_term_exchange_receipt_events_v1(receipt_id, event_sequence desc, event_id desc);
create index if not exists idx_world_term_exchange_receipt_events_finalized_v1
    on public.world_term_exchange_receipt_events_v1(finalized_at desc, event_id desc);
create index if not exists idx_world_term_exchange_receipt_events_intent_v1
    on public.world_term_exchange_receipt_events_v1(intent_id, finalized_at desc, event_id desc);
create unique index if not exists uq_world_term_exchange_receipt_events_initial_intent_v1
    on public.world_term_exchange_receipt_events_v1(intent_id)
    where event_sequence = 1;

-- A partially-applied rollout may already contain history rows.  Do not
-- silently preserve a forked intent under two receipt ids: abort the upgrade
-- before exposing a mixed authority view.  Valid legacy rows (one receipt id
-- per intent, including a NULL/unknown amount) continue through backfill.
do $duplicate_guard$
begin
    if exists (
        select 1
          from public.league_term_exchange_receipt_events_v1
         group by intent_id
        having count(distinct receipt_id) > 1
    ) then
        raise exception 'normalized league receipt history contains multiple receipt_ids for one intent';
    end if;
    if exists (
        select 1
          from public.world_term_exchange_receipt_events_v1
         group by intent_id
        having count(distinct receipt_id) > 1
    ) then
        raise exception 'normalized world receipt history contains multiple receipt_ids for one intent';
    end if;
end
$duplicate_guard$;

-- Validate the typed columns, JSON evidence, hash, and per-receipt hash chain
-- before an event becomes visible.  TG_TABLE_NAME is restricted to the two
-- table names by the trigger declarations below and is quoted in the dynamic
-- lookup, so callers cannot select an arbitrary relation.
create or replace function public.cex_validate_term_exchange_receipt_event_v1()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $function$
declare
    latest_event record;
    latest_intent_event record;
    projection_row record;
    intent_row record;
    immutable_amount bigint;
    immutable_amount_present boolean := false;
    immutable_amount_invalid boolean := false;
    projection_table text;
begin
    if new.receipt_json is null or jsonb_typeof(new.receipt_json) <> 'object' then
        raise exception 'normalized term exchange receipt event JSON must be an object';
    end if;

    if new.receipt_json ->> 'protocol_version' is distinct from new.protocol_version
       or new.receipt_json ->> 'receipt_id' is distinct from new.receipt_id
       or new.receipt_json ->> 'intent_id' is distinct from new.intent_id
       or new.receipt_json ->> 'term_id' is distinct from new.term_id
       or new.receipt_json ->> 'backend_id' is distinct from new.backend_id
       or new.receipt_json ->> 'backend_kind' is distinct from new.backend_kind
       or new.receipt_json ->> 'status' is distinct from new.status
       or new.receipt_json ->> 'progression_class' is distinct from new.progression_class
       or new.receipt_json ->> 'settlement_reference' is distinct from new.settlement_reference
       or new.receipt_json ->> 'ledger_entry_id' is distinct from new.ledger_entry_id
       or new.receipt_json ->> 'reason' is distinct from new.reason
       -- JSONB represents an explicit JSON null as the jsonb value `null`,
       -- whereas to_jsonb(NULL::bigint) is SQL NULL.  Normalize both sides
       -- so legacy projections with an unknown amount can be backfilled and
       -- remain fail-closed at value-authority callers.
       or jsonb_typeof(new.receipt_json -> 'amount_credits') is distinct from
          (case when new.amount_credits is null then 'null' else 'number' end)
       or (new.receipt_json ->> 'amount_credits') !~ '^-?[0-9]+$'
       or coalesce(new.receipt_json -> 'amount_credits', 'null'::jsonb)
          is distinct from coalesce(to_jsonb(new.amount_credits), 'null'::jsonb)
       or new.receipt_json ->> 'finalized_at_epoch' is distinct from
          (extract(epoch from new.finalized_at)::bigint)::text then
        raise exception 'normalized term exchange receipt event JSON binding mismatch';
    end if;

    -- When this game receipt is also backed by a durable native intent, the
    -- immutable intent amount is the only value authority.  The native intent
    -- amount is optional for audit-only commands; a present value must be a
    -- non-negative JSON integer.  Invalid/negative intent amounts fail closed:
    -- they may only produce a NULL/zero projection, never a positive amount.
    select intent_json -> 'amount_credits' as amount_json
      into intent_row
      from public.trnm_economic_intents
     where intent_id = new.intent_id;
    if found and intent_row.amount_json is not null
       and jsonb_typeof(intent_row.amount_json) <> 'null' then
        immutable_amount_present := true;
        if jsonb_typeof(intent_row.amount_json) <> 'number'
           or (intent_row.amount_json #>> '{}') !~ '^-?[0-9]+$' then
            immutable_amount_invalid := true;
        else
            begin
                immutable_amount := (intent_row.amount_json #>> '{}')::bigint;
            exception when others then
                immutable_amount_invalid := true;
            end;
            if immutable_amount is null or immutable_amount < 0 then
                immutable_amount_invalid := true;
            end if;
        end if;
    end if;
    if immutable_amount_invalid then
        if new.amount_credits is not null and new.amount_credits <> 0 then
            raise exception 'normalized receipt amount is not authorized by an invalid immutable intent amount';
        end if;
    elsif immutable_amount_present
          and new.amount_credits is distinct from immutable_amount then
        raise exception 'normalized receipt amount does not match immutable intent amount';
    end if;

    -- A receipt id is the intent-level retry identity.  Check by intent_id in
    -- addition to the receipt-id hash-chain lookup below; otherwise a caller
    -- could fork one intent into two independent receipt histories.  The
    -- projection check closes the first-event gap when a projection row was
    -- written before its history row during a partial rollout.
    execute format(
        'select event_id, receipt_id, event_sequence, amount_credits
           from public.%I
          where intent_id = $1
          order by event_sequence desc, event_id desc
          limit 1',
        tg_table_name
    )
    into latest_intent_event
    using new.intent_id;
    if latest_intent_event.event_id is not null then
        if new.receipt_id is distinct from latest_intent_event.receipt_id then
            raise exception 'normalized receipt_id must remain stable for an intent';
        end if;
        if latest_intent_event.amount_credits is not null
           and new.amount_credits is distinct from latest_intent_event.amount_credits then
            raise exception 'normalized receipt amount must remain stable for an intent';
        end if;
    end if;

    projection_table := case tg_table_name
        when 'league_term_exchange_receipt_events_v1' then 'league_term_exchange_receipts'
        when 'world_term_exchange_receipt_events_v1' then 'world_term_exchange_receipts'
        else null
    end;
    if projection_table is not null then
        execute format(
            'select receipt_id, amount_credits
               from public.%I
              where intent_id = $1
              order by updated_at desc, receipt_id
              limit 1',
            projection_table
        )
        into projection_row
        using new.intent_id;
        if projection_row.receipt_id is not null then
            if new.receipt_id is distinct from projection_row.receipt_id then
                raise exception 'normalized receipt_id conflicts with immutable projection identity';
            end if;
            if projection_row.amount_credits is not null
               and new.amount_credits is distinct from projection_row.amount_credits then
                raise exception 'normalized receipt amount conflicts with immutable projection amount';
            end if;
        end if;
    end if;

    if new.receipt_hash is distinct from
       'sha256:' || encode(digest(new.receipt_json::text, 'sha256'), 'hex') then
        raise exception 'normalized term exchange receipt event hash mismatch';
    end if;

    execute format(
        'select event_id, event_sequence, receipt_hash,
                protocol_version, intent_id, term_id, backend_id, backend_kind,
                progression_class, amount_credits
           from public.%I
          where receipt_id = $1
          order by event_sequence desc, event_id desc
          limit 1',
        tg_table_name
    )
    into latest_event
    using new.receipt_id;

    -- `EXECUTE ... INTO` does not provide a reliable `FOUND` value across
    -- PostgreSQL versions when the target is a record.  The primary key is
    -- non-null for every real predecessor, so inspect the record field
    -- directly to distinguish the first event from an append.
    if latest_event.event_id is null then
        if new.event_sequence <> 1 or new.previous_receipt_hash is not null then
            raise exception 'first normalized term exchange receipt event must start sequence one';
        end if;
        if new.event_kind not in ('initial', 'backfill') then
            raise exception 'first normalized term exchange receipt event must be initial or backfill';
        end if;
    else
        -- A receipt id is the retry identity.  Its immutable protocol/intent
        -- binding may not change between a hold and a later final snapshot;
        -- only outcome fields (status, reason, ledger entry, amount evidence)
        -- are allowed to evolve.  This closes the otherwise silent
        -- ON-CONFLICT/append path that could attach a different intent to an
        -- existing receipt id.
        if new.protocol_version is distinct from latest_event.protocol_version
           or new.intent_id is distinct from latest_event.intent_id
           or new.term_id is distinct from latest_event.term_id
           or new.backend_id is distinct from latest_event.backend_id
           or new.backend_kind is distinct from latest_event.backend_kind then
            raise exception 'normalized term exchange receipt event immutable identity mismatch';
        end if;
        if latest_event.amount_credits is not null
           and new.amount_credits is distinct from latest_event.amount_credits then
            raise exception 'normalized term exchange receipt amount chain mismatch';
        end if;
        -- Only a recoverable hold is retryable.  Allowed, skipped, and hard
        -- fail classes are terminal for this receipt identity and must never
        -- be followed by a later hold/final transition.
        if latest_event.progression_class is distinct from 'recoverable_hold' then
            raise exception 'normalized terminal receipt event cannot append after final progression';
        end if;
        if new.event_sequence <> latest_event.event_sequence + 1 then
            raise exception 'normalized term exchange receipt event sequence must append contiguously';
        end if;
        if new.previous_receipt_hash is distinct from latest_event.receipt_hash then
            raise exception 'normalized term exchange receipt event hash chain mismatch';
        end if;
        if new.event_kind in ('initial', 'backfill') then
            raise exception 'normalized term exchange receipt retry cannot be initial/backfill';
        end if;
    end if;

    if (case
            when new.status in (
                'reserved', 'settled', 'reopened_settled', 'consumed', 'refunded',
                'seller_chargeback_reserved', 'seller_chargeback_consumed',
                'approved_release', 'duplicate'
            ) then 'progression_allowed'
            when new.status in (
                'skipped_zero_price', 'skipped_zero_reward', 'skipped_zero_seller_net'
            ) then 'terminal_skip'
            when new.status in (
                'held_review', 'skipped_missing_room', 'failed_network', 'failed_identity',
                'failed_ledger', 'seller_chargeback_reserve_failed',
                'seller_chargeback_failed', 'rejected_refund_failed',
                'cancelled_refund_failed'
            ) then 'recoverable_hold'
            when new.status in (
                'failed_bad_response', 'skipped_missing_account',
                'skipped_missing_ledger_token', 'missing_account', 'missing_ledger_token'
            ) then 'hard_fail'
            else null
        end) is distinct from new.progression_class then
        raise exception 'normalized receipt status/progression mapping mismatch';
    end if;

    return new;
end
$function$;

create or replace function public.cex_reject_term_exchange_receipt_event_mutation_v1()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $function$
begin
    raise exception using
        errcode = '55000',
        message = 'normalized term exchange receipt event history is append-only';
end;
$function$;

drop trigger if exists trg_cex_validate_league_term_exchange_receipt_event_v1
    on public.league_term_exchange_receipt_events_v1;
create trigger trg_cex_validate_league_term_exchange_receipt_event_v1
before insert on public.league_term_exchange_receipt_events_v1
for each row
execute function public.cex_validate_term_exchange_receipt_event_v1();

drop trigger if exists trg_cex_validate_world_term_exchange_receipt_event_v1
    on public.world_term_exchange_receipt_events_v1;
create trigger trg_cex_validate_world_term_exchange_receipt_event_v1
before insert on public.world_term_exchange_receipt_events_v1
for each row
execute function public.cex_validate_term_exchange_receipt_event_v1();

drop trigger if exists trg_cex_reject_league_term_exchange_receipt_event_mutation_v1
    on public.league_term_exchange_receipt_events_v1;
create trigger trg_cex_reject_league_term_exchange_receipt_event_mutation_v1
before update or delete on public.league_term_exchange_receipt_events_v1
for each statement
execute function public.cex_reject_term_exchange_receipt_event_mutation_v1();

drop trigger if exists trg_cex_reject_world_term_exchange_receipt_event_mutation_v1
    on public.world_term_exchange_receipt_events_v1;
create trigger trg_cex_reject_world_term_exchange_receipt_event_mutation_v1
before update or delete on public.world_term_exchange_receipt_events_v1
for each statement
execute function public.cex_reject_term_exchange_receipt_event_mutation_v1();

drop trigger if exists trg_cex_reject_league_term_exchange_receipt_event_truncate_v1
    on public.league_term_exchange_receipt_events_v1;
create trigger trg_cex_reject_league_term_exchange_receipt_event_truncate_v1
before truncate on public.league_term_exchange_receipt_events_v1
for each statement
execute function public.cex_reject_term_exchange_receipt_event_mutation_v1();

drop trigger if exists trg_cex_reject_world_term_exchange_receipt_event_truncate_v1
    on public.world_term_exchange_receipt_events_v1;
create trigger trg_cex_reject_world_term_exchange_receipt_event_truncate_v1
before truncate on public.world_term_exchange_receipt_events_v1
for each statement
execute function public.cex_reject_term_exchange_receipt_event_mutation_v1();

alter table public.league_term_exchange_receipt_events_v1
    enable always trigger trg_cex_validate_league_term_exchange_receipt_event_v1;
alter table public.league_term_exchange_receipt_events_v1
    enable always trigger trg_cex_reject_league_term_exchange_receipt_event_mutation_v1;
alter table public.league_term_exchange_receipt_events_v1
    enable always trigger trg_cex_reject_league_term_exchange_receipt_event_truncate_v1;
alter table public.world_term_exchange_receipt_events_v1
    enable always trigger trg_cex_validate_world_term_exchange_receipt_event_v1;
alter table public.world_term_exchange_receipt_events_v1
    enable always trigger trg_cex_reject_world_term_exchange_receipt_event_mutation_v1;
alter table public.world_term_exchange_receipt_events_v1
    enable always trigger trg_cex_reject_world_term_exchange_receipt_event_truncate_v1;

-- Validate rows that predate this trigger definition before the idempotent
-- projection backfill can skip them.  A history row with the same receipt id
-- but a different initial identity/amount is still a split authority, even
-- though `NOT EXISTS (receipt_id)` would otherwise leave it untouched.  NULL
-- amounts remain compatible legacy unknowns; two known amounts must agree.
do $projection_parity_guard$
begin
    if exists (
        select 1
          from public.league_term_exchange_receipts p
          join public.league_term_exchange_receipt_events_v1 e
            on e.receipt_id = p.receipt_id
           and e.event_sequence = 1
         where p.protocol_version is distinct from e.protocol_version
            or p.intent_id is distinct from e.intent_id
            or p.term_id is distinct from e.term_id
            or p.backend_id is distinct from e.backend_id
            or p.backend_kind is distinct from e.backend_kind
            or (p.amount_credits is not null
                and p.amount_credits is distinct from e.amount_credits)
    ) then
        raise exception 'normalized league receipt history/projection identity or amount conflict';
    end if;
    if exists (
        select 1
          from public.world_term_exchange_receipts p
          join public.world_term_exchange_receipt_events_v1 e
            on e.receipt_id = p.receipt_id
           and e.event_sequence = 1
         where p.protocol_version is distinct from e.protocol_version
            or p.intent_id is distinct from e.intent_id
            or p.term_id is distinct from e.term_id
            or p.backend_id is distinct from e.backend_id
            or p.backend_kind is distinct from e.backend_kind
            or (p.amount_credits is not null
                and p.amount_credits is distinct from e.amount_credits)
    ) then
        raise exception 'normalized world receipt history/projection identity or amount conflict';
    end if;
end
$projection_parity_guard$;

-- Seed sequence one from the immutable 0026 projection.  This is deliberately
-- idempotent so an interrupted/partially-applied deployment can be retried.
insert into public.league_term_exchange_receipt_events_v1 (
    receipt_id, event_sequence, event_kind, previous_receipt_hash,
    protocol_version, intent_id, term_id, backend_id, backend_kind, status,
    progression_class, settlement_reference, ledger_entry_id, reason,
    amount_credits, finalized_at, receipt_json, receipt_hash, created_at
)
select r.receipt_id,
       1,
       'backfill',
       null,
       r.protocol_version,
       r.intent_id,
       r.term_id,
       r.backend_id,
       r.backend_kind,
       r.status,
       r.progression_class,
       r.settlement_reference,
       r.ledger_entry_id,
       r.reason,
       r.amount_credits,
       r.finalized_at,
       jsonb_build_object(
           'protocol_version', r.protocol_version,
           'receipt_id', r.receipt_id,
           'intent_id', r.intent_id,
           'term_id', r.term_id,
           'backend_id', r.backend_id,
           'backend_kind', r.backend_kind,
           'status', r.status,
           'progression_class', r.progression_class,
           'settlement_reference', r.settlement_reference,
           'ledger_entry_id', r.ledger_entry_id,
           'reason', r.reason,
           'amount_credits', r.amount_credits,
           'finalized_at_epoch', extract(epoch from r.finalized_at)::bigint
       ),
       'sha256:' || encode(digest(jsonb_build_object(
           'protocol_version', r.protocol_version,
           'receipt_id', r.receipt_id,
           'intent_id', r.intent_id,
           'term_id', r.term_id,
           'backend_id', r.backend_id,
           'backend_kind', r.backend_kind,
           'status', r.status,
           'progression_class', r.progression_class,
           'settlement_reference', r.settlement_reference,
           'ledger_entry_id', r.ledger_entry_id,
           'reason', r.reason,
           'amount_credits', r.amount_credits,
           'finalized_at_epoch', extract(epoch from r.finalized_at)::bigint
       )::text, 'sha256'), 'hex'),
       r.created_at
  from public.league_term_exchange_receipts r
 where not exists (
           select 1
             from public.league_term_exchange_receipt_events_v1 e
            where e.receipt_id = r.receipt_id
       );

insert into public.world_term_exchange_receipt_events_v1 (
    receipt_id, event_sequence, event_kind, previous_receipt_hash,
    protocol_version, intent_id, term_id, backend_id, backend_kind, status,
    progression_class, settlement_reference, ledger_entry_id, reason,
    amount_credits, finalized_at, receipt_json, receipt_hash, created_at
)
select r.receipt_id,
       1,
       'backfill',
       null,
       r.protocol_version,
       r.intent_id,
       r.term_id,
       r.backend_id,
       r.backend_kind,
       r.status,
       r.progression_class,
       r.settlement_reference,
       r.ledger_entry_id,
       r.reason,
       r.amount_credits,
       r.finalized_at,
       jsonb_build_object(
           'protocol_version', r.protocol_version,
           'receipt_id', r.receipt_id,
           'intent_id', r.intent_id,
           'term_id', r.term_id,
           'backend_id', r.backend_id,
           'backend_kind', r.backend_kind,
           'status', r.status,
           'progression_class', r.progression_class,
           'settlement_reference', r.settlement_reference,
           'ledger_entry_id', r.ledger_entry_id,
           'reason', r.reason,
           'amount_credits', r.amount_credits,
           'finalized_at_epoch', extract(epoch from r.finalized_at)::bigint
       ),
       'sha256:' || encode(digest(jsonb_build_object(
           'protocol_version', r.protocol_version,
           'receipt_id', r.receipt_id,
           'intent_id', r.intent_id,
           'term_id', r.term_id,
           'backend_id', r.backend_id,
           'backend_kind', r.backend_kind,
           'status', r.status,
           'progression_class', r.progression_class,
           'settlement_reference', r.settlement_reference,
           'ledger_entry_id', r.ledger_entry_id,
           'reason', r.reason,
           'amount_credits', r.amount_credits,
           'finalized_at_epoch', extract(epoch from r.finalized_at)::bigint
       )::text, 'sha256'), 'hex'),
       r.created_at
  from public.world_term_exchange_receipts r
 where not exists (
           select 1
             from public.world_term_exchange_receipt_events_v1 e
            where e.receipt_id = r.receipt_id
       );

revoke update, delete, truncate
    on table public.league_term_exchange_receipt_events_v1,
               public.world_term_exchange_receipt_events_v1
    from public;

do $do$
begin
    if exists (select 1 from pg_roles where rolname = 'cex_projection_operator') then
        execute 'revoke update, delete, truncate on table public.league_term_exchange_receipt_events_v1, public.world_term_exchange_receipt_events_v1 from cex_projection_operator';
    end if;
end
$do$;

comment on table public.league_term_exchange_receipt_events_v1 is
    'Append-only league Term Exchange receipt snapshots; latest is event_sequence/event_id descending';
comment on table public.world_term_exchange_receipt_events_v1 is
    'Append-only world Term Exchange receipt snapshots; recoverable holds append final retries';
comment on column public.league_term_exchange_receipt_events_v1.receipt_hash is
    'sha256 digest of canonical receipt_json; previous_receipt_hash links the append-only chain';
comment on column public.world_term_exchange_receipt_events_v1.receipt_hash is
    'sha256 digest of canonical receipt_json; previous_receipt_hash links the append-only chain';

commit;
