#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

MANIFEST_PATH="ops/monitoring/monitoring-bundle-manifest.example.yml"
MODE="write"
BUNDLE_KIND="all"

usage() {
  cat <<'EOF'
Usage: scripts/assemble-monitoring-bundles.sh [--manifest <path>] [--check] [--bundle all|prometheus|alertmanager]

Assembles the repo-local combined monitoring bundles from
ops/monitoring/monitoring-bundle-manifest.example.yml.

Default behavior:
  - reads the manifest
  - regenerates the combined Prometheus / Alertmanager bundles
  - writes them back to the combinedBundle paths declared in the manifest

Options:
  --manifest <path>    Override manifest path (default: ops/monitoring/monitoring-bundle-manifest.example.yml)
  --check              Do not write; exit non-zero if assembled output differs from current bundle files
  --bundle <kind>      One of: all, prometheus, alertmanager (default: all)
  -h, --help           Show this help

Examples:
  ./scripts/assemble-monitoring-bundles.sh
  ./scripts/assemble-monitoring-bundles.sh --check
  ./scripts/assemble-monitoring-bundles.sh --bundle prometheus
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --manifest)
      [[ $# -ge 2 ]] || { echo "Error: --manifest requires a path" >&2; exit 2; }
      MANIFEST_PATH="$2"
      shift 2
      ;;
    --check)
      MODE="check"
      shift
      ;;
    --bundle)
      [[ $# -ge 2 ]] || { echo "Error: --bundle requires one of all|prometheus|alertmanager" >&2; exit 2; }
      BUNDLE_KIND="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$BUNDLE_KIND" in
  all|prometheus|alertmanager) ;;
  *)
    echo "Error: --bundle must be one of all|prometheus|alertmanager" >&2
    exit 2
    ;;
esac

python3 - "$REPO_ROOT" "$MANIFEST_PATH" "$MODE" "$BUNDLE_KIND" <<'PY'
from __future__ import annotations

import sys
from pathlib import Path
import yaml

repo_root = Path(sys.argv[1])
manifest_arg = sys.argv[2]
mode = sys.argv[3]
bundle_kind = sys.argv[4]

manifest_path = Path(manifest_arg)
if not manifest_path.is_absolute():
    manifest_path = repo_root / manifest_path
if not manifest_path.exists():
    raise SystemExit(f"Error: manifest not found: {manifest_path}")

manifest = yaml.safe_load(manifest_path.read_text(encoding='utf-8')) or {}
if not isinstance(manifest, dict):
    raise SystemExit("Error: manifest must be a YAML object")


def repo_path(rel_or_abs: str) -> Path:
    path = Path(rel_or_abs)
    return path if path.is_absolute() else repo_root / path


def load_yaml_from_manifest_path(rel_or_abs: str):
    path = repo_path(rel_or_abs)
    if not path.exists():
        raise SystemExit(f"Error: referenced file not found: {path}")
    with path.open('r', encoding='utf-8') as f:
        return yaml.safe_load(f) or {}, path


def build_header(kind: str, sources: list[str]) -> str:
    lines = [
        f"# Generated by scripts/assemble-monitoring-bundles.sh from {manifest_path.relative_to(repo_root)}",
        f"# Bundle kind: {kind}",
        "# Source files:",
    ]
    lines.extend(f"# - {src}" for src in sources)
    return "\n".join(lines) + "\n\n"


prom_cfg = manifest.get('prometheus') or {}
alert_cfg = manifest.get('alertmanager') or {}

prom_files = prom_cfg.get('files') or []
alert_files = alert_cfg.get('files') or []

if not isinstance(prom_files, list) or not isinstance(alert_files, list):
    raise SystemExit("Error: manifest prometheus.files and alertmanager.files must be arrays")


def assemble_prometheus() -> tuple[str, Path]:
    groups = []
    source_paths: list[str] = []
    for entry in prom_files:
        if not isinstance(entry, dict) or 'path' not in entry:
            raise SystemExit("Error: every prometheus manifest entry must include path")
        data, _path = load_yaml_from_manifest_path(entry['path'])
        source_paths.append(entry['path'])
        entry_groups = data.get('groups') or []
        if not isinstance(entry_groups, list):
            raise SystemExit(f"Error: {entry['path']} must contain a groups array")
        groups.extend(entry_groups)

    combined = {'groups': groups}
    target = repo_path(prom_cfg.get('combinedBundle'))
    text = build_header('prometheus', source_paths) + yaml.safe_dump(
        combined,
        sort_keys=False,
        allow_unicode=True,
    )
    return text, target


ROUTE_BASE_KEYS = ['receiver', 'group_by', 'group_wait', 'group_interval', 'repeat_interval']


def dedupe_receivers(receivers: list[dict]) -> list[dict]:
    seen = set()
    result = []
    for receiver in receivers:
        name = receiver.get('name')
        if name in seen:
            continue
        seen.add(name)
        result.append(receiver)
    return result



def assemble_alertmanager() -> tuple[str, Path]:
    configs = []
    source_paths: list[str] = []
    for entry in alert_files:
        if not isinstance(entry, dict) or 'path' not in entry:
            raise SystemExit("Error: every alertmanager manifest entry must include path")
        data, _path = load_yaml_from_manifest_path(entry['path'])
        source_paths.append(entry['path'])
        if 'route' not in data:
            raise SystemExit(f"Error: {entry['path']} must contain a route object")
        configs.append(data)

    first_route = configs[0].get('route') or {}
    route_base = {key: first_route.get(key) for key in ROUTE_BASE_KEYS}
    for idx, cfg in enumerate(configs[1:], start=2):
        route = cfg.get('route') or {}
        for key in ROUTE_BASE_KEYS:
            if route.get(key) != route_base.get(key):
                raise SystemExit(
                    f"Error: alertmanager route base mismatch for key '{key}' in manifest entry #{idx}"
                )

    routes = []
    receivers = []
    inhibit_rules = []
    for cfg in configs:
        route = cfg.get('route') or {}
        routes.extend(route.get('routes') or [])
        receivers.extend(cfg.get('receivers') or [])
        inhibit_rules.extend(cfg.get('inhibit_rules') or [])

    combined = {
        'route': {**route_base, 'routes': routes},
        'receivers': dedupe_receivers(receivers),
        'inhibit_rules': inhibit_rules,
    }
    target = repo_path(alert_cfg.get('combinedBundle'))
    text = build_header('alertmanager', source_paths) + yaml.safe_dump(
        combined,
        sort_keys=False,
        allow_unicode=True,
    )
    return text, target


assembled = []
if bundle_kind in ('all', 'prometheus'):
    assembled.append(('prometheus',) + assemble_prometheus())
if bundle_kind in ('all', 'alertmanager'):
    assembled.append(('alertmanager',) + assemble_alertmanager())

if mode == 'write':
    for kind, text, target in assembled:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding='utf-8')
        rel = target.relative_to(repo_root) if target.is_relative_to(repo_root) else target
        print(f"wrote {kind} bundle -> {rel}")
else:
    drift = []
    for kind, text, target in assembled:
        current = target.read_text(encoding='utf-8') if target.exists() else None
        if current != text:
            drift.append((kind, target))
    if drift:
        for kind, target in drift:
            rel = target.relative_to(repo_root) if target.is_relative_to(repo_root) else target
            print(f"drift: {kind} bundle differs -> {rel}", file=sys.stderr)
        raise SystemExit(1)
    print("ok: monitoring bundles match manifest assembly")
PY
