#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/_dev-helpers.sh
source "$SCRIPT_DIR/_dev-helpers.sh"

OUT_DIR="${CEX_LOCAL_PRODUCTION_ENV_DIR:-$CEX_PROJECT_ROOT/run/local-production}"
ENV_PATH="${CEX_LOCAL_PRODUCTION_ENV_PATH:-$OUT_DIR/.env}"
FORCE=0

usage() {
  cat <<EOF
Usage: scripts/bootstrap-local-production-env.sh [--force]

Generate an ignored local production-posture env file for exercising the strict
production readiness gate on this machine. Values are high-entropy local secrets
for validation only; replace them in real deployments.

Default output: $ENV_PATH

Then run, for example:
  CEX_ENV_FILE=$ENV_PATH ./scripts/runtime-manager-linux.sh restart
  CEX_ENV_FILE=$ENV_PATH CEX_PROVIDER_PROBE_MODEL=google/gemini-2.5-flash ./scripts/check-production-readiness.sh
EOF
}

while (($#)); do
  case "$1" in
    --force)
      FORCE=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown arg: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
  shift
done

if [[ -f "$ENV_PATH" && "$FORCE" != "1" ]]; then
  echo "local production env already exists: $ENV_PATH" >&2
  echo "use --force to overwrite" >&2
  exit 0
fi

mkdir -p "$OUT_DIR/edge" "$OUT_DIR/config" "$OUT_DIR/logs" "$OUT_DIR/openclaw"
chmod 700 "$OUT_DIR" "$OUT_DIR/edge" "$OUT_DIR/config" "$OUT_DIR/logs" "$OUT_DIR/openclaw"

python3 - <<'PY' "$ENV_PATH" "$OUT_DIR"
import json
import secrets
import sys
from pathlib import Path

env_path = Path(sys.argv[1])
out_dir = Path(sys.argv[2])
org_id = "00000000-0000-0000-0000-00000000ce01"

def token(prefix: str) -> str:
    return f"{prefix}_{secrets.token_urlsafe(32)}"

gateway_key = token("cex_gateway")
identity_admin = token("identity_admin")
audit_read = token("audit_read")
execution_admin = token("execution_admin")
ledger_admin = token("ledger_admin")
consumer_ingress = token("consumer_ingress")
matrix_ingress = token("matrix_ingress")
session_secret = token("session_secret")

identity_static_api_keys = [{
    "api_key": gateway_key,
    "org_id": org_id,
    "actor_id": "local-production-entry",
    "actor_label": "Local Production Entry"
}]
identity_admin_tokens = [{
    "token": identity_admin,
    "actor_id": "local-production-identity-admin",
    "actor_label": "Local Production Identity Admin",
    "scopes": ["api_keys:manage", "api_keys:read"],
    "org_ids": [org_id]
}]
audit_admin_tokens = [{
    "token": audit_read,
    "actor_id": "local-production-audit-reader",
    "actor_label": "Local Production Audit Reader",
    "scopes": ["audit:read"],
    "org_ids": [org_id]
}]
execution_admin_tokens = [{
    "token": execution_admin,
    "actor_id": "local-production-execution-admin",
    "actor_label": "Local Production Execution Admin",
    "scopes": ["executions:manage", "executions:read"],
    "org_ids": [org_id]
}]
ledger_admin_tokens = [{
    "token": ledger_admin,
    "actor_id": "local-production-ledger-admin",
    "actor_label": "Local Production Ledger Admin",
    "scopes": ["ledger:manage", "ledger:read"],
    "org_ids": [org_id]
}]

lines = [
    "# Generated by scripts/bootstrap-local-production-env.sh",
    "# Local production-posture validation only. Do not copy these secrets to real deployments.",
    "APP_ENV=production",
    "RUST_LOG=info",
    "GATEWAY_HOST=127.0.0.1",
    "GATEWAY_PORT=8080",
    "LEDGER_BASE_URL=http://127.0.0.1:7002",
    "EXECUTION_BASE_URL=http://127.0.0.1:7003",
    "IDENTITY_BASE_URL=http://127.0.0.1:7001",
    "AUDIT_BASE_URL=http://127.0.0.1:7004",
    "CAPABILITY_BASE_URL=http://127.0.0.1:7005",
    "CONSUMER_ENTRY_BASE_URL=http://127.0.0.1:8090",
    "MATRIX_ENTRY_BASE_URL=http://127.0.0.1:8091",
    "DATABASE_URL=postgres://postgres:postgres@localhost:5432/cex_ai",
    f"OPENCLAW_STATE_DIR={out_dir / 'openclaw'}",
    f"OPENCLAW_CONFIG_PATH={out_dir / 'openclaw/openclaw.json'}",
    f"OPENCLAW_AGENT_DIR={out_dir / 'openclaw/agents/cex/agent'}",
    f"CAPABILITY_OPENCLAW_MODELS_JSON_PATH={out_dir / 'openclaw/agents/cex/agent/models.json'}",
    "OPENCLAW_CEX_EXTRA_MODELS=google/gemini-2.5-flash",
    "CEX_PROVIDER_PROBE_MODEL=google/gemini-2.5-flash",
    f"CEX_GATEWAY_API_KEY={gateway_key}",
    f"IDENTITY_STATIC_API_KEYS_JSON={json.dumps(identity_static_api_keys, separators=(',', ':'))}",
    f"IDENTITY_ADMIN_TOKENS_JSON={json.dumps(identity_admin_tokens, separators=(',', ':'))}",
    f"AUDIT_ADMIN_TOKENS_JSON={json.dumps(audit_admin_tokens, separators=(',', ':'))}",
    f"EXECUTION_ADMIN_TOKENS_JSON={json.dumps(execution_admin_tokens, separators=(',', ':'))}",
    f"LEDGER_ADMIN_TOKENS_JSON={json.dumps(ledger_admin_tokens, separators=(',', ':'))}",
    f"EXECUTION_ADMIN_TOKEN={execution_admin}",
    f"EXECUTION_WORKER_ADMIN_TOKEN={execution_admin}",
    "CEX_ENABLE_QUEUED_WORKER=1",
    "EXECUTION_WORKER_ID=cex-local-production-worker",
    "EXECUTION_CLAIM_LEASE_SECONDS=300",
    "EXECUTION_PROVIDER_DISPATCH_TIMEOUT_SECONDS=60",
    "EXECUTION_QUEUED_WORKER_MAX_ATTEMPTS=3",
    f"CONSUMER_ENTRY_INGRESS_TOKEN={consumer_ingress}",
    f"MATRIX_ENTRY_INGRESS_TOKEN={matrix_ingress}",
    "CONSUMER_ENTRY_REQUIRE_SESSION_AUTH=true",
    "CONSUMER_ENTRY_REQUIRE_IDENTITY_BINDING=true",
    f"CONSUMER_ENTRY_REPLAY_STORE_PATH={out_dir / 'edge/consumer-entry-replay.json'}",
    f"CONSUMER_ENTRY_RATE_LIMIT_STORE_PATH={out_dir / 'edge/consumer-entry-rate-limit.json'}",
    f"MATRIX_ENTRY_RECENT_EVENT_STORE_PATH={out_dir / 'edge/matrix-entry-recent-events.json'}",
    f"CONSUMER_ENTRY_IDENTITY_BINDING_AUDIT_LOG_PATH={out_dir / 'logs/identity-binding-audit.jsonl'}",
    "CONSUMER_ENTRY_IDENTITY_BINDING_RELOAD_REQUIRE_REVISION=true",
    "CONSUMER_ENTRY_IDENTITY_BINDING_RELOAD_REQUIRE_APPROVED_REVISION=true",
    "CONSUMER_ENTRY_IDENTITY_BINDING_RELOAD_REQUIRE_ACTOR=true",
    "CONSUMER_ENTRY_IDENTITY_BINDING_RELOAD_ALLOWED_ACTORS=cex-runtime-manager",
    "CONSUMER_ENTRY_SESSION_AUTH_SECRET=" + session_secret,
    "CONSUMER_ENTRY_SESSION_AUTH_ALLOWED_ISSUERS=matrix-entry-adapter",
    "CONSUMER_ENTRY_SESSION_AUTH_EXPECTED_AUDIENCE=consumer-entry-api",
    "MATRIX_ENTRY_CONSUMER_SESSION_AUTH_SECRET=" + session_secret,
    "MATRIX_ENTRY_CONSUMER_SESSION_AUTH_ISSUER=matrix-entry-adapter",
    "MATRIX_ENTRY_CONSUMER_SESSION_AUTH_AUDIENCE=consumer-entry-api",
    "MATRIX_ENTRY_CONSUMER_SESSION_AUTH_TTL_SECS=300",
    f"EXECUTION_POLICY_BUNDLE_PATH={out_dir / 'config/execution-policy.json'}",
    "CEX_REQUIRED_BLOCK_CAPABILITY_PREFIXES=cap.openclaw.model.minimax.,cap.openclaw.model.openai-codex.",
    "CEX_READINESS_MODE=production",
]

env_path.write_text("\n".join(lines) + "\n")
print(json.dumps({
    "env_path": str(env_path),
    "out_dir": str(out_dir),
    "gateway_key_prefix": gateway_key[:18],
    "execution_admin_prefix": execution_admin[:22],
}, indent=2))
PY

chmod 600 "$ENV_PATH"
cp "$CEX_PROJECT_ROOT/config/execution-policy.production.example.json" "$OUT_DIR/config/execution-policy.json"
chmod 600 "$OUT_DIR/config/execution-policy.json"
OPENCLAW_STATE_DIR="$OUT_DIR/openclaw" \
OPENCLAW_CONFIG_PATH="$OUT_DIR/openclaw/openclaw.json" \
OPENCLAW_AGENT_DIR="$OUT_DIR/openclaw/agents/cex/agent" \
OPENCLAW_CEX_EXTRA_MODELS="google/gemini-2.5-flash" \
bash "$SCRIPT_DIR/bootstrap-openclaw-cex.sh" >/dev/null

cat <<EOF

Wrote local production-posture env: $ENV_PATH
Use:
  CEX_ENV_FILE=$ENV_PATH ./scripts/runtime-manager-linux.sh restart
  CEX_ENV_FILE=$ENV_PATH CEX_PROVIDER_PROBE_MODEL=google/gemini-2.5-flash ./scripts/check-production-readiness.sh
EOF
