#!/usr/bin/env python3
"""Collect exact-tree P0 evidence and emit a repository-qualified candidate manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import subprocess
import time
import tomllib
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Keep the safety helper importable when this file is loaded through
# ``importlib`` by the repository self-tests rather than executed directly.
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))
from evidence_safe_io import (  # noqa: E402
    SafeIOError,
    prepare_collect_targets,
    read_json_nofollow,
    read_regular_nofollow,
    safe_io_self_test,
    sha256_file_nofollow,
    write_json_nofollow,
)

REQUIRED_GATES = {
    "p0-migration-gate": ".github/workflows/p0-migration-gate.yml",
    "rust-service-gate": ".github/workflows/rust-service-gate.yml",
    "p0-gateway-exact-reserve-gate": ".github/workflows/p0-gateway-exact-reserve-gate.yml",
    "p0-execution-settlement-gate": ".github/workflows/p0-execution-settlement-gate.yml",
    "p0-provider-reconciliation-gate": ".github/workflows/p0-provider-reconciliation-gate.yml",
}
QUALIFICATION_SCOPE = (
    "repository-exact-money-control-plane-plus-hepta-durability-doc-integrity-full-suite-lint-receipt-recovery-and-trnm-production-config-hardening"
)
TRIGGER_RELATIVE_PATH = "docs/release-evidence/p0-candidate-trigger.json"
# Hosted evidence is only authoritative when produced by a branch-tree event.
# Pull-request runs can share a commit SHA with the candidate branch but are
# evaluated against a merge ref and therefore do not prove the checked-out
# branch tree.  Keep this allow-list intentionally narrow and fail closed if
# GitHub introduces another event type.
AUTHORITATIVE_RUN_EVENTS = {"push", "workflow_dispatch"}
LOCAL_EVIDENCE = {
    "candidate-hygiene": "candidate-hygiene.json",
    # These two attestations are generated by the Rust service gate.  Keep
    # them as first-class manifest entries instead of relying on their being
    # present somewhere in the opaque payload directory; otherwise the
    # candidate manifest could qualify without naming the repository-integrity
    # and strict Hepta recovery controls required by v12 Blocks H/I.
    "repository-integrity": "repository-integrity.json",
    "hepta-postgres-integration": "hepta-postgres-integration.json",
    "migration-and-lifecycle-matrix": "database-lifecycle.json",
    "exact-ledger-soak": "exact-ledger-soak.json",
    "backup-restore": "backup-restore.json",
}
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
GIT_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
MIGRATION_RE = re.compile(r"^(\d{4})_[a-z0-9][a-z0-9._-]*\.sql$")
MAX_GATE_POLL_ATTEMPTS = 480
MAX_GATE_POLL_INTERVAL_SECONDS = 60
MAX_GATE_POLL_SECONDS = 2 * 60 * 60


def canonical_payload_name(sha: str, run_attempt: int) -> str:
    return f"cex-p0-evidence-{sha}-attempt-{run_attempt}"


def is_positive_int(value: Any) -> bool:
    """Return whether a JSON value is a real positive integer (not boolean)."""

    return isinstance(value, int) and not isinstance(value, bool) and value > 0


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def sha256_bytes(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    try:
        return sha256_file_nofollow(path)
    except SafeIOError as error:
        raise SystemExit(str(error)) from error


def write_json(path: Path, value: Any) -> None:
    try:
        write_json_nofollow(path, value)
    except SafeIOError as error:
        raise SystemExit(str(error)) from error


def qualification_scope(root: Path) -> str:
    """Read the immutable candidate scope from the shared trigger.

    The trigger is the single operator-visible qualification contract.  Keeping
    the generated manifest bound to it prevents a stale generator constant
    from silently narrowing (or widening) what the hosted evidence claims.
    """

    trigger_path = root / TRIGGER_RELATIVE_PATH
    try:
        trigger = read_json_nofollow(trigger_path, label="candidate trigger")
    except SafeIOError as error:
        raise SystemExit(f"cannot read candidate trigger scope: {error}") from error
    scope = trigger.get("qualification_scope") if isinstance(trigger, dict) else None
    if not isinstance(scope, str) or not scope.strip():
        raise SystemExit("candidate trigger qualification_scope must be a non-empty string")
    scope = scope.strip()
    if scope != QUALIFICATION_SCOPE:
        raise SystemExit(
            "candidate trigger qualification_scope is not the generator's v12 scope"
        )
    return scope


def run_git(root: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(root), *args],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def migration_state(root: Path) -> tuple[Path, str]:
    numbered: list[tuple[int, str, Path]] = []
    for path in (root / "migrations").glob("*.sql"):
        match = MIGRATION_RE.fullmatch(path.name)
        if match:
            numbered.append((int(match.group(1)), path.name, path))
    if not numbered:
        raise SystemExit("no numbered migrations found")
    numbered.sort()
    digest = hashlib.sha256()
    for _, name, path in numbered:
        digest.update(name.encode("utf-8"))
        digest.update(b"\0")
        try:
            # The migration chain is part of the immutable provenance record;
            # reject symlinked/replaced files instead of hashing a redirected
            # target through a path-based read.
            digest.update(read_regular_nofollow(path))
        except SafeIOError as error:
            raise SystemExit(f"cannot read migration {name} safely: {error}") from error
        digest.update(b"\0")
    return numbered[-1][2], "sha256:" + digest.hexdigest()


def api_json(url: str, token: str) -> dict[str, Any]:
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "User-Agent": "cex-p0-release-evidence",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def _run_sort_key(run: dict[str, Any]) -> tuple[str, str, int, int]:
    """Return a stable newest-first sort key for a workflow run.

    GitHub normally returns integer ``id``/``run_attempt`` values, but keeping
    this conversion defensive means a malformed (or test-double) response
    cannot make evidence collection crash while trying to report the run.
    """

    def as_int(value: Any) -> int:
        try:
            return int(value or 0)
        except (TypeError, ValueError):
            return 0

    return (
        str(run.get("updated_at") or ""),
        str(run.get("created_at") or ""),
        as_int(run.get("run_attempt")),
        as_int(run.get("id")),
    )


def _workflow_runs(
    repository: str,
    sha: str,
    branch: str,
    token: str,
) -> list[dict[str, Any]]:
    """Read all workflow-run pages for one exact SHA and branch.

    ``head_sha`` alone is not sufficient here: the repository can have many
    branch refs pointing at the same commit, and each ref may have a separate
    run.  The API's ``branch`` filter narrows the response, while the caller
    still performs an exact ``head_branch`` check before selecting evidence.
    Pagination is intentionally handled here rather than relying on the
    default first page (which can silently omit an older successful run).
    """

    per_page = 100
    page = 1
    runs_by_id: dict[int, dict[str, Any]] = {}
    runs_without_id: list[dict[str, Any]] = []
    endpoint = f"https://api.github.com/repos/{repository}/actions/runs"

    while True:
        url = endpoint + "?" + urllib.parse.urlencode(
            {
                "head_sha": sha,
                "branch": branch,
                "per_page": per_page,
                "page": page,
            }
        )
        payload = api_json(url, token)
        page_runs = payload.get("workflow_runs")
        if not isinstance(page_runs, list):
            raise SystemExit("GitHub Actions response lacks workflow_runs")

        for run in page_runs:
            if not isinstance(run, dict):
                continue
            try:
                run_id = int(run.get("id"))
            except (TypeError, ValueError):
                runs_without_id.append(run)
            else:
                # A run should occur on exactly one page.  Deduplicating by
                # id makes collection deterministic if a run is moved between
                # pages while the API is being polled.
                runs_by_id[run_id] = run

        if not page_runs:
            break

        total_count: int | None = None
        try:
            if payload.get("total_count") is not None:
                total_count = int(payload["total_count"])
        except (TypeError, ValueError):
            total_count = None

        # The normal GitHub response gives either a short final page or a
        # total_count.  If neither is useful, fetch one empty page and stop;
        # this is conservative and also works with lightweight API doubles.
        if (total_count is not None and page * per_page >= total_count) or (
            total_count is None and len(page_runs) < per_page
        ):
            break
        page += 1
        # A broken API response must not make a release job loop forever.
        if page > 1000:
            raise SystemExit("GitHub Actions pagination exceeded 1000 pages")

    return list(runs_by_id.values()) + runs_without_id


def collect_gate_runs(
    repository: str,
    sha: str,
    token: str,
    attempts: int,
    interval_seconds: int,
    *,
    branch: str,
) -> dict[str, dict[str, Any]]:
    if not branch:
        raise SystemExit("branch is required to bind hosted gate evidence")

    for attempt in range(1, attempts + 1):
        all_runs = _workflow_runs(repository, sha, branch, token)

        selected: dict[str, dict[str, Any]] = {}
        pending: list[str] = []
        failures: list[str] = []
        for name, path in REQUIRED_GATES.items():
            candidates = [
                run
                for run in all_runs
                if run.get("head_sha") == sha and run.get("path") == path
                and run.get("head_branch") == branch
                and run.get("event") in AUTHORITATIVE_RUN_EVENTS
            ]
            if not candidates:
                pending.append(f"{name}:missing(branch={branch})")
                continue

            # The newest authoritative run is the only run that can qualify
            # this exact branch/SHA.  An older success must never mask a newer
            # failed, cancelled, skipped, or in-progress rerun: doing so would
            # let a candidate silently revert to stale evidence.  This mirrors
            # check-hosted-gate-execution.py, which independently attests the
            # same latest-run binding; the strict wrapper consumes this frozen
            # context rather than selecting a second run after collection.
            run = max(candidates, key=_run_sort_key)
            status = str(run.get("status") or "unknown").lower()
            conclusion = str(run.get("conclusion") or "unknown").lower()
            if status != "completed":
                pending.append(
                    f"{name}:{status}:run={run.get('id')}:"
                    f"attempt={run.get('run_attempt')}"
                )
                continue
            if conclusion != "success":
                failures.append(
                    f"{name}:{conclusion}:run={run.get('id')}:"
                    f"attempt={run.get('run_attempt')}"
                )
                continue
            selected[name] = run

        if failures:
            raise SystemExit("authoritative hosted gate failed: " + ", ".join(failures))
        if len(selected) == len(REQUIRED_GATES):
            # The run-list response and the job-level hosted checker are
            # separate API observations.  Re-read the selected runs (including
            # the latest-run policy) immediately before treating them as an
            # immutable evidence snapshot.  A newer rerun, branch move, or
            # post-selection status change must fail closed instead of being
            # silently mixed into the manifest.
            return revalidate_gate_runs(
                repository,
                sha,
                branch,
                token,
                selected,
            )
        print(
            f"gate evidence poll {attempt}/{attempts}: "
            + (", ".join(pending) if pending else "waiting"),
            flush=True,
        )
        if attempt < attempts:
            time.sleep(interval_seconds)
    raise SystemExit("timed out waiting for exact-tree authoritative hosted gates")


def _run_snapshot(run: dict[str, Any], *, label: str) -> dict[str, Any]:
    """Extract the immutable identity/status fields used for TOCTOU checks."""

    try:
        run_id = int(run.get("id"))
        run_attempt = int(run.get("run_attempt"))
    except (TypeError, ValueError) as error:
        raise SystemExit(f"{label} has an invalid run identity") from error
    if run_id <= 0 or run_attempt <= 0:
        raise SystemExit(f"{label} has an invalid run identity")
    required = (
        "path",
        "head_sha",
        "head_branch",
        "event",
        "status",
        "conclusion",
        "created_at",
        "updated_at",
    )
    missing = [field for field in required if run.get(field) is None]
    if missing:
        raise SystemExit(f"{label} is missing run field(s): {', '.join(missing)}")
    return {
        "id": run_id,
        "run_attempt": run_attempt,
        "path": str(run["path"]),
        "head_sha": str(run["head_sha"]),
        "head_branch": str(run["head_branch"]),
        "event": str(run["event"]),
        "status": str(run["status"]).lower(),
        "conclusion": str(run["conclusion"]).lower(),
        "created_at": str(run["created_at"]),
        "updated_at": str(run["updated_at"]),
    }


def _assert_run_snapshot_equal(
    expected: dict[str, Any],
    observed: dict[str, Any],
    *,
    label: str,
) -> None:
    expected_snapshot = _run_snapshot(expected, label=f"{label} expected")
    observed_snapshot = _run_snapshot(observed, label=f"{label} observed")
    if expected_snapshot != observed_snapshot:
        raise SystemExit(
            f"{label} changed during evidence binding: "
            f"expected={expected_snapshot!r} observed={observed_snapshot!r}"
        )


def revalidate_gate_runs(
    repository: str,
    sha: str,
    branch: str,
    token: str,
    selected: dict[str, dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    """Re-read the latest run and its detail record for every selected gate.

    GitHub exposes run lists and run details through independent eventually
    consistent endpoints.  Binding a manifest from only the first list result
    permits a newer rerun (or a metadata/status change) to race the write.  A
    second latest-run snapshot plus per-run detail comparison makes that race
    observable and fail closed.  The returned detail records are the values
    written into the context, so the evidence payload is tied to the final
    observation rather than an earlier API response.
    """

    latest_runs = _workflow_runs(repository, sha, branch, token)
    details: dict[str, dict[str, Any]] = {}
    for name, workflow_path in REQUIRED_GATES.items():
        candidates = [
            run
            for run in latest_runs
            if isinstance(run, dict)
            and run.get("head_sha") == sha
            and run.get("path") == workflow_path
            and run.get("head_branch") == branch
            and run.get("event") in AUTHORITATIVE_RUN_EVENTS
        ]
        if not candidates:
            raise SystemExit(
                f"hosted gate {name} disappeared during evidence binding"
            )
        observed_latest = max(candidates, key=_run_sort_key)
        expected = selected.get(name)
        if not isinstance(expected, dict):
            raise SystemExit(f"hosted gate {name} was not selected")
        _assert_run_snapshot_equal(
            expected,
            observed_latest,
            label=f"hosted gate {name} latest run",
        )

        run_id = int(observed_latest["id"])
        detail_url = f"https://api.github.com/repos/{repository}/actions/runs/{run_id}"
        detail = api_json(detail_url, token)
        _assert_run_snapshot_equal(
            observed_latest,
            detail,
            label=f"hosted gate {name} detail",
        )
        status = str(detail.get("status") or "unknown").lower()
        conclusion = str(detail.get("conclusion") or "unknown").lower()
        if status != "completed" or conclusion != "success":
            raise SystemExit(
                f"hosted gate {name} is no longer a completed success "
                f"({status}/{conclusion})"
            )
        details[name] = detail

    # A rerun can be created while the per-run detail requests above are in
    # flight.  Take one final list snapshot after the last detail response and
    # compare every gate again; otherwise a newer failed/in-progress run could
    # appear immediately after the first list response and remain invisible to
    # this binding pass.  The manifest step invokes this function immediately
    # before writing, so this final observation is the last run-selection check.
    final_runs = _workflow_runs(repository, sha, branch, token)
    for name, workflow_path in REQUIRED_GATES.items():
        candidates = [
            run
            for run in final_runs
            if isinstance(run, dict)
            and run.get("head_sha") == sha
            and run.get("path") == workflow_path
            and run.get("head_branch") == branch
            and run.get("event") in AUTHORITATIVE_RUN_EVENTS
        ]
        if not candidates:
            raise SystemExit(f"hosted gate {name} disappeared in final binding snapshot")
        observed_final = max(candidates, key=_run_sort_key)
        expected = selected.get(name)
        if not isinstance(expected, dict):
            raise SystemExit(f"hosted gate {name} was not selected")
        _assert_run_snapshot_equal(
            expected,
            observed_final,
            label=f"hosted gate {name} final run",
        )
        detail = details[name]
        _assert_run_snapshot_equal(
            observed_final,
            detail,
            label=f"hosted gate {name} final detail",
        )
    return details


def self_test() -> list[str]:
    """Exercise the run-snapshot TOCTOU guard without contacting GitHub.

    The collector is normally driven by GitHub's Actions API, so a regression
    in the second-observation guard can otherwise remain hidden until a real
    candidate run.  Keep this fixture entirely in-process: replacing the two
    API seams lets the test prove that a stable snapshot succeeds while a
    newer run or a changed detail record fails closed.
    """

    failures: list[str] = list(safe_io_self_test())
    branch = "feature/evidence"
    sha = "a" * 40
    base_runs: list[dict[str, Any]] = []
    for index, workflow_path in enumerate(REQUIRED_GATES.values(), start=1):
        base_runs.append(
            {
                "id": 1000 + index,
                "run_attempt": 1,
                "path": workflow_path,
                "head_sha": sha,
                "head_branch": branch,
                "event": "push",
                "status": "completed",
                "conclusion": "success",
                "created_at": f"2026-08-30T00:0{index}:00Z",
                "updated_at": f"2026-08-30T00:0{index}:01Z",
            }
        )
    selected = {
        name: next(run for run in base_runs if run["path"] == workflow_path)
        for name, workflow_path in REQUIRED_GATES.items()
    }

    original_runs = _workflow_runs
    original_api = api_json
    try:
        def stable_runs(
            _repository: str, _sha: str, _branch: str, _token: str
        ) -> list[dict[str, Any]]:
            return [dict(run) for run in base_runs]

        def stable_api(url: str, _token: str) -> dict[str, Any]:
            run_id = int(url.rstrip("/").rsplit("/", 1)[-1])
            return dict(next(run for run in base_runs if run["id"] == run_id))

        globals()["_workflow_runs"] = stable_runs
        globals()["api_json"] = stable_api
        result = revalidate_gate_runs("org/repo", sha, branch, "token", selected)
        if set(result) != set(REQUIRED_GATES):
            failures.append("stable run snapshot was not accepted")

        newer_failure = dict(base_runs[0])
        newer_failure.update(
            {
                "id": 9001,
                "conclusion": "failure",
                "created_at": "2026-08-30T01:00:00Z",
                "updated_at": "2026-08-30T01:00:01Z",
            }
        )

        def newer_runs(
            _repository: str, _sha: str, _branch: str, _token: str
        ) -> list[dict[str, Any]]:
            return [newer_failure if run["path"] == newer_failure["path"] else dict(run) for run in base_runs]

        globals()["_workflow_runs"] = newer_runs
        try:
            revalidate_gate_runs("org/repo", sha, branch, "token", selected)
        except SystemExit:
            pass
        else:
            failures.append("newer failed rerun was accepted")

        late_snapshot_calls = 0

        def late_newer_runs(
            _repository: str, _sha: str, _branch: str, _token: str
        ) -> list[dict[str, Any]]:
            nonlocal late_snapshot_calls
            late_snapshot_calls += 1
            if late_snapshot_calls == 1:
                return [dict(run) for run in base_runs]
            return [
                newer_failure
                if run["path"] == newer_failure["path"]
                else dict(run)
                for run in base_runs
            ]

        globals()["_workflow_runs"] = late_newer_runs
        globals()["api_json"] = stable_api
        try:
            revalidate_gate_runs("org/repo", sha, branch, "token", selected)
        except SystemExit:
            pass
        else:
            failures.append("late failed rerun after detail loop was accepted")

        def changed_detail_api(url: str, _token: str) -> dict[str, Any]:
            payload = stable_api(url, _token)
            if payload["id"] == base_runs[0]["id"]:
                payload["status"] = "in_progress"
                payload["conclusion"] = "unknown"
            return payload

        globals()["_workflow_runs"] = stable_runs
        globals()["api_json"] = changed_detail_api
        try:
            revalidate_gate_runs("org/repo", sha, branch, "token", selected)
        except SystemExit:
            pass
        else:
            failures.append("changed run detail was accepted")
    finally:
        globals()["_workflow_runs"] = original_runs
        globals()["api_json"] = original_api
    return failures


def run_self_test(_args: argparse.Namespace) -> int:
    failures = self_test()
    if failures:
        raise SystemExit("release-evidence core self-test failed: " + "; ".join(failures))
    print(json.dumps({"schema": "cex.p0-release-evidence-core-self-test.v1", "status": "ok"}))
    return 0


def generate_sbom(
    root: Path,
    output: Path,
    repository: str,
    sha: str,
    run_id: int,
    run_attempt: int = 1,
) -> None:
    try:
        cargo_lock_bytes = read_regular_nofollow(root / "Cargo.lock")
        lock = tomllib.loads(cargo_lock_bytes.decode("utf-8"))
    except (SafeIOError, UnicodeDecodeError, tomllib.TOMLDecodeError) as error:
        raise SystemExit(f"Cargo.lock is not a safe valid TOML file: {error}") from error
    raw_packages = lock.get("package")
    if not isinstance(raw_packages, list) or not raw_packages:
        raise SystemExit("Cargo.lock contains no packages")
    packages: list[dict[str, Any]] = []
    relationships: list[dict[str, str]] = []
    for index, package in enumerate(raw_packages, start=1):
        name = str(package["name"])
        version = str(package["version"])
        safe = re.sub(r"[^A-Za-z0-9.-]", "-", f"{name}-{version}-{index}")
        spdx_id = f"SPDXRef-Package-{safe}"
        item: dict[str, Any] = {
            "SPDXID": spdx_id,
            "name": name,
            "versionInfo": version,
            "downloadLocation": str(package.get("source") or "NOASSERTION"),
            "filesAnalyzed": False,
            "licenseConcluded": "NOASSERTION",
            "licenseDeclared": "NOASSERTION",
            "copyrightText": "NOASSERTION",
            "externalRefs": [
                {
                    "referenceCategory": "PACKAGE-MANAGER",
                    "referenceType": "purl",
                    "referenceLocator": f"pkg:cargo/{urllib.parse.quote(name)}@{urllib.parse.quote(version)}",
                }
            ],
        }
        checksum = package.get("checksum")
        if isinstance(checksum, str) and SHA256_RE.fullmatch(checksum):
            item["checksums"] = [{"algorithm": "SHA256", "checksumValue": checksum}]
        packages.append(item)
        relationships.append(
            {
                "spdxElementId": "SPDXRef-DOCUMENT",
                "relationshipType": "DESCRIBES",
                "relatedSpdxElement": spdx_id,
            }
        )
    write_json(
        output,
        {
            "spdxVersion": "SPDX-2.3",
            "dataLicense": "CC0-1.0",
            "SPDXID": "SPDXRef-DOCUMENT",
            "name": f"CEX P0 candidate {sha}",
            "documentNamespace": (
                f"https://github.com/{repository}/p0-sbom/{sha}/{run_id}"
                f"/attempt/{run_attempt}"
            ),
            "creationInfo": {
                "created": utc_now(),
                "creators": ["Tool: cex-p0-release-evidence"],
                "licenseListVersion": "3.25",
            },
            "packages": packages,
            "relationships": relationships,
        },
    )


def local_evidence_is_successful(name: str, payload: Any) -> bool:
    if not isinstance(payload, dict):
        return False
    status = payload.get("status")
    if status is not None and status not in {"ok", "passed", "success"}:
        # Never let a contradictory ``{"ok": true, "status": "failed"}``
        # record qualify a candidate.  Producers should emit one coherent
        # status, but the collector is the last fail-closed boundary.
        return False
    if payload.get("ok") is True:
        return True
    if status in {"ok", "passed", "success"}:
        return True
    return False


def collect(args: argparse.Namespace) -> int:
    root = args.repo_root.resolve()
    # Keep caller paths lexical until the no-follow boundary has checked every
    # component.  Resolving an attacker-controlled symlink first would erase
    # the evidence of the substitution and redirect all subsequent writes.
    evidence_dir = args.evidence_dir if args.evidence_dir.is_absolute() else Path.cwd() / args.evidence_dir
    context_path = args.context if args.context.is_absolute() else Path.cwd() / args.context
    if not GIT_SHA_RE.fullmatch(args.sha) or not GIT_SHA_RE.fullmatch(args.tree):
        raise SystemExit("sha and tree must be 40 lowercase hex")
    run_attempt = int(getattr(args, "run_attempt", 1))
    if run_attempt < 1:
        raise SystemExit("run-attempt must be a positive integer")
    if args.run_id < 1:
        raise SystemExit("run-id must be a positive integer")
    if run_git(root, "rev-parse", "HEAD") != args.sha:
        raise SystemExit("requested evidence SHA does not match checked out HEAD")
    if run_git(root, "rev-parse", "HEAD^{tree}") != args.tree:
        raise SystemExit("requested evidence tree does not match checked out tree")
    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        raise SystemExit("GITHUB_TOKEN is required to bind hosted gate evidence")

    try:
        prepare_collect_targets(
            evidence_dir,
            context_path,
            input_files=tuple(evidence_dir / relative for relative in LOCAL_EVIDENCE.values()),
            output_files=(context_path,),
            output_directories=(evidence_dir / "hosted-gates",),
        )
    except SafeIOError as error:
        raise SystemExit(str(error)) from error
    for name, relative in LOCAL_EVIDENCE.items():
        path = evidence_dir / relative
        try:
            payload = read_json_nofollow(path, label=f"local evidence {name}")
        except SafeIOError as error:
            raise SystemExit(str(error)) from error
        if not local_evidence_is_successful(name, payload):
            raise SystemExit(f"local evidence is not successful: {name}")
        commit_sha = payload.get("commit_sha")
        if commit_sha != args.sha:
            raise SystemExit(f"local evidence {name} is not bound to the exact commit")
        tree_sha = payload.get("tree_sha")
        if not isinstance(tree_sha, str) or not GIT_SHA_RE.fullmatch(tree_sha):
            raise SystemExit(f"local evidence {name} lacks a valid exact tree_sha")
        if tree_sha != args.tree:
            raise SystemExit(f"local evidence {name} is bound to a different tree")

    attempts = int(os.environ.get("CEX_P0_GATE_POLL_ATTEMPTS", "360"))
    interval = int(os.environ.get("CEX_P0_GATE_POLL_INTERVAL_SECONDS", "15"))
    if (
        attempts < 1
        or attempts > MAX_GATE_POLL_ATTEMPTS
        or interval < 1
        or interval > MAX_GATE_POLL_INTERVAL_SECONDS
        or attempts * interval > MAX_GATE_POLL_SECONDS
    ):
        raise SystemExit(
            "gate polling bounds are invalid "
            f"(attempts 1..{MAX_GATE_POLL_ATTEMPTS}, "
            f"interval 1..{MAX_GATE_POLL_INTERVAL_SECONDS}s, "
            f"total <= {MAX_GATE_POLL_SECONDS}s)"
        )
    runs = collect_gate_runs(
        args.repository,
        args.sha,
        token,
        attempts,
        interval,
        branch=args.branch,
    )

    gate_records: dict[str, dict[str, Any]] = {}
    gates_dir = evidence_dir / "hosted-gates"
    for name, path in REQUIRED_GATES.items():
        run = runs[name]
        record = {
            "schema": "cex.hosted-gate-evidence.v1",
            "name": name,
            "workflow_path": path,
            "repository": args.repository,
            "branch": args.branch,
            "head_sha": args.sha,
            "head_branch": run.get("head_branch"),
            "run_id": int(run["id"]),
            "run_attempt": int(run.get("run_attempt") or 0),
            "event": run.get("event"),
            "status": run.get("status"),
            "conclusion": run.get("conclusion"),
            "created_at": run.get("created_at"),
            "updated_at": run.get("updated_at"),
            "html_url": run.get("html_url"),
        }
        if record["run_id"] <= 0 or record["run_attempt"] <= 0:
            raise SystemExit(f"hosted gate {name} has an invalid run identity")
        path_out = gates_dir / f"{name}.json"
        write_json(path_out, record)
        # Keep the complete immutable run identity in the release context.
        # The manifest validator intentionally does not trust the per-file
        # payload alone: it must be able to prove that every selected run is
        # for this repository, branch, workflow, and exact commit before it
        # emits a candidate manifest.  Previously only the payload pointer and
        # URL were retained here, which made the final manifest step reject
        # every otherwise-successful hosted qualification.
        gate_records[name] = {
            **record,
            "path": path_out.relative_to(evidence_dir).as_posix(),
            "sha256": sha256_file(path_out),
        }

    migration_head, migration_chain_sha256 = migration_state(root)
    cargo_sha256 = sha256_file(root / "Cargo.lock")
    sbom_path = evidence_dir / "sbom.spdx.json"
    generate_sbom(root, sbom_path, args.repository, args.sha, args.run_id, run_attempt)
    provenance_path = evidence_dir / "provenance.intoto.json"
    write_json(
        provenance_path,
        {
            "_type": "https://in-toto.io/Statement/v1",
            "subject": [
                {
                    "name": args.repository,
                    "digest": {"gitCommit": args.sha, "gitTree": args.tree},
                }
            ],
            "predicateType": "https://slsa.dev/provenance/v1",
            "predicate": {
                "buildDefinition": {
                    "buildType": "https://github.com/TrillionniumFoundation/CEX/p0-release-candidate-gate/v1",
                    "externalParameters": {
                        "repository": args.repository,
                        "branch": args.branch,
                        "commit_sha": args.sha,
                        "workflow_run_id": args.run_id,
                        "workflow_run_attempt": run_attempt,
                    },
                    "internalParameters": {"migration_head": migration_head.name},
                    "resolvedDependencies": [
                        {
                            "uri": f"git+https://github.com/{args.repository}@{args.sha}",
                            "digest": {"gitCommit": args.sha, "gitTree": args.tree},
                        },
                        {"uri": "file:Cargo.lock", "digest": {"sha256": cargo_sha256[7:]}},
                        {
                            "uri": "file:migrations/",
                            "digest": {"sha256": migration_chain_sha256[7:]},
                        },
                    ],
                },
                "runDetails": {
                    "builder": {"id": "https://github.com/actions/runner"},
                    "metadata": {
                        "invocationId": (
                            f"{args.server_url}/{args.repository}/actions/runs/{args.run_id}"
                            f"/attempts/{run_attempt}"
                        ),
                        "startedOn": utc_now(),
                    },
                },
            },
        },
    )

    files: dict[str, str] = {}
    for path in sorted(evidence_dir.rglob("*")):
        if path.is_file() and path.name != "payload-index.json":
            files[path.relative_to(evidence_dir).as_posix()] = sha256_file(path)
    payload_index_path = evidence_dir / "payload-index.json"
    write_json(
        payload_index_path,
        {
            "schema": "cex.p0-release-evidence-payload.v1",
            "repository": args.repository,
            "branch": args.branch,
            "commit_sha": args.sha,
            "tree_sha": args.tree,
            "workflow_run_id": args.run_id,
            "workflow_run_attempt": run_attempt,
            "payload_name": canonical_payload_name(args.sha, run_attempt),
            "generated_at": utc_now(),
            "files": files,
        },
    )
    files["payload-index.json"] = sha256_file(payload_index_path)

    context = {
        "repository": args.repository,
        "branch": args.branch,
        "commit_sha": args.sha,
        "tree_sha": args.tree,
        "workflow_run_id": args.run_id,
        "workflow_run_attempt": run_attempt,
        "payload_name": canonical_payload_name(args.sha, run_attempt),
        # The aggregate upload step supplies the immutable artifact digest
        # later.  The strict manifest command fills this field before final
        # context binding; leaving it explicit prevents a missing digest from
        # being mistaken for an optional value.
        "payload_digest": None,
        "server_url": args.server_url,
        "generated_at": utc_now(),
        "cargo_lock_sha256": cargo_sha256,
        "migration_head": migration_head.name,
        "migration_sha256": sha256_file(migration_head),
        "migration_chain_sha256": migration_chain_sha256,
        "files": files,
        "hosted_gates": gate_records,
        "qualification_scope": qualification_scope(root),
    }
    write_json(context_path, context)
    print(context_path)
    return 0


def normalize_digest(value: str) -> str:
    raw = value.strip().lower()
    if raw.startswith("sha256:"):
        raw = raw[7:]
    if not SHA256_RE.fullmatch(raw):
        raise SystemExit("payload digest must be a canonical SHA-256")
    return "sha256:" + raw


def validate_hosted_gate_context(context: dict[str, Any]) -> None:
    """Fail closed if hosted gate records are not bound to one branch/SHA."""

    hosted = context.get("hosted_gates")
    if not isinstance(hosted, dict):
        raise SystemExit("release context lacks hosted_gates")
    if set(hosted) != set(REQUIRED_GATES):
        raise SystemExit("release context hosted_gates do not match required gates")

    repository = context.get("repository")
    branch = context.get("branch")
    sha = context.get("commit_sha")
    workflow_run_id = context.get("workflow_run_id")
    if not isinstance(repository, str) or not repository:
        raise SystemExit("release context repository is missing")
    if not isinstance(branch, str) or not branch:
        raise SystemExit("release context branch is missing")
    if not isinstance(sha, str) or not GIT_SHA_RE.fullmatch(sha):
        raise SystemExit("release context commit_sha is invalid")
    tree = context.get("tree_sha")
    if not isinstance(tree, str) or not GIT_SHA_RE.fullmatch(tree):
        raise SystemExit("release context tree_sha is invalid")
    if not is_positive_int(workflow_run_id):
        raise SystemExit("release context workflow_run_id is invalid")
    run_attempt = context.get("workflow_run_attempt")
    if not is_positive_int(run_attempt):
        raise SystemExit("release context workflow_run_attempt is invalid")
    payload_name = context.get("payload_name")
    expected_payload_name = canonical_payload_name(sha, run_attempt)
    if payload_name != expected_payload_name:
        raise SystemExit("release context payload_name is not bound to its SHA/attempt")

    for name, expected_path in REQUIRED_GATES.items():
        record = hosted.get(name)
        if not isinstance(record, dict):
            raise SystemExit(f"release context hosted gate is invalid: {name}")
        if record.get("repository") != repository:
            raise SystemExit(f"hosted gate {name} is bound to a different repository")
        if record.get("workflow_path") != expected_path:
            raise SystemExit(f"hosted gate {name} has an unexpected workflow path")
        if record.get("branch") != branch or record.get("head_branch") != branch:
            raise SystemExit(f"hosted gate {name} is bound to a different branch")
        if record.get("head_sha") != sha:
            raise SystemExit(f"hosted gate {name} is bound to a different commit")
        if record.get("event") not in AUTHORITATIVE_RUN_EVENTS:
            raise SystemExit(
                f"hosted gate {name} was not produced by an authoritative branch event"
            )
        if record.get("status") != "completed" or record.get("conclusion") != "success":
            raise SystemExit(f"hosted gate {name} is not a completed success")
        if not is_positive_int(record.get("run_id")):
            raise SystemExit(f"hosted gate {name} has an invalid run id")
        if not is_positive_int(record.get("run_attempt")):
            raise SystemExit(f"hosted gate {name} has an invalid run attempt")


def manifest(args: argparse.Namespace) -> int:
    try:
        context = read_json_nofollow(args.context, label="release context")
    except SafeIOError as error:
        raise SystemExit(str(error)) from error
    if not isinstance(context, dict):
        raise SystemExit("release context must be an object")
    validate_hosted_gate_context(context)
    # The strict wrapper freezes and verifies the hosted run/job snapshot
    # before upload.  In that mode the manifest must consume the immutable
    # context rather than selecting a second latest run after the artifact
    # boundary; otherwise a rerun could replace the evidence between collect
    # and manifest.  The legacy core CLI retains its historical revalidation
    # behavior unless this explicit flag is supplied.
    if not getattr(args, "frozen_hosted_context", False):
        token = os.environ.get("GITHUB_TOKEN", "")
        if not token:
            raise SystemExit(
                "GITHUB_TOKEN is required to revalidate hosted gate evidence before manifest binding"
            )
        selected_context: dict[str, dict[str, Any]] = {}
        for name, record in context["hosted_gates"].items():
            if not isinstance(record, dict):
                raise SystemExit(f"release context hosted gate is invalid: {name}")
            selected_context[name] = {
                "id": record.get("run_id"),
                "run_attempt": record.get("run_attempt"),
                "path": record.get("workflow_path"),
                "head_sha": record.get("head_sha"),
                "head_branch": record.get("head_branch"),
                "event": record.get("event"),
                "status": record.get("status"),
                "conclusion": record.get("conclusion"),
                "created_at": record.get("created_at"),
                "updated_at": record.get("updated_at"),
            }
        revalidate_gate_runs(
            str(context["repository"]),
            str(context["commit_sha"]),
            str(context["branch"]),
            token,
            selected_context,
        )
    expected_payload_name = context["payload_name"]
    if args.payload_name != expected_payload_name:
        raise SystemExit(
            "payload name does not match the exact release run attempt "
            f"(expected {expected_payload_name})"
        )
    payload_digest = normalize_digest(args.payload_digest)
    payload_uri = (
        f"gh://{context['repository']}/actions/runs/{context['workflow_run_id']}"
        f"/attempts/{context['workflow_run_attempt']}/artifacts/{args.payload_name}"
    )
    files = context["files"]
    evidence: list[dict[str, Any]] = []
    for name in REQUIRED_GATES:
        gate = context["hosted_gates"][name]
        evidence.append(
            {
                "name": f"hosted:{name}",
                "status": "pass",
                "uri": (
                    f"gh://{context['repository']}/actions/runs/{gate['run_id']}"
                    f"/attempts/{gate['run_attempt']}"
                ),
                "sha256": gate["sha256"],
                "waiver": None,
            }
        )
    for name, relative in LOCAL_EVIDENCE.items():
        evidence.append(
            {
                "name": name,
                "status": "pass",
                "uri": f"artifact://{args.payload_name}/{relative}",
                "sha256": files[relative],
                "waiver": None,
            }
        )

    data = {
        "schema": "cex.release-baseline-manifest.v1",
        "status": "candidate",
        "qualification_scope": context["qualification_scope"],
        "production_ready": False,
        "production_authorization": "not_granted",
        "project_id": "hepta-control-plane",
        "release_id": args.release_id,
        "generated_at": utc_now(),
        "source": {
            "repository": context["repository"],
            "branch": context["branch"],
            "commit_sha": context["commit_sha"],
            "tree_sha": context["tree_sha"],
        },
        "dependencies": {"cargo_lock_sha256": context["cargo_lock_sha256"]},
        "database": {
            "migration_head": context["migration_head"],
            "migration_sha256": context["migration_sha256"],
            "migration_chain_sha256": context["migration_chain_sha256"],
        },
        "build": {
            "workflow_run_id": context["workflow_run_id"],
            "artifacts": [
                {
                    "name": args.payload_name,
                    "uri": payload_uri,
                    "sha256": payload_digest,
                }
            ],
            "images": [],
            "sbom": {
                "name": "sbom.spdx.json",
                "uri": f"artifact://{args.payload_name}/sbom.spdx.json",
                "sha256": files["sbom.spdx.json"],
            },
            "provenance": {
                "name": "provenance.intoto.json",
                "uri": f"artifact://{args.payload_name}/provenance.intoto.json",
                "sha256": files["provenance.intoto.json"],
            },
        },
        "evidence": evidence,
        "approvals": [
            {
                "role": "repository-qualification-automation",
                "actor": "github-actions[bot]",
                "decision": "approve",
                "decided_at": utc_now(),
                "scope": "repository candidate only; not production, financial, security, legal, or operations approval",
            }
        ],
        "external_gates": {
            "status": "independent_approval_required",
            "items": [
                "X1: production-like backup and restore rehearsal against representative data volume and the real storage topology",
                "X2: deployment/cutover and rollback rehearsal with real service identities, network policy and secret custody",
                "X3: real provider reconciliation artifacts for success, definite non-execution and indeterminate outcome",
                "X4: credential issuance, rotation, revocation and break-glass custody review",
                "X5: sustained production-like soak/endurance run with queue age, retry, reconciliation, parity and Audit delivery SLOs",
                "X6: independent security, operations and financial-control review",
                "X7: legal, commercial or provider approvals where the production integration requires them",
                "X8: final human go/no-go decision bound to the immutable release candidate",
            ],
        },
        "revocation": None,
    }
    write_json(args.output, data)
    print(args.output)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    collect_parser = subparsers.add_parser("collect")
    collect_parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    collect_parser.add_argument("--evidence-dir", required=True, type=Path)
    collect_parser.add_argument("--context", required=True, type=Path)
    collect_parser.add_argument("--repository", required=True)
    collect_parser.add_argument("--branch", required=True)
    collect_parser.add_argument("--sha", required=True)
    collect_parser.add_argument("--tree", required=True)
    collect_parser.add_argument("--run-id", required=True, type=int)
    collect_parser.add_argument("--run-attempt", required=True, type=int)
    collect_parser.add_argument("--server-url", required=True)
    collect_parser.set_defaults(function=collect)

    manifest_parser = subparsers.add_parser("manifest")
    manifest_parser.add_argument("--context", required=True, type=Path)
    manifest_parser.add_argument("--output", required=True, type=Path)
    manifest_parser.add_argument("--release-id", required=True)
    manifest_parser.add_argument("--payload-name", required=True)
    manifest_parser.add_argument("--payload-digest", required=True)
    manifest_parser.add_argument(
        "--frozen-hosted-context",
        action="store_true",
        help="trust the already verified context snapshot without selecting new runs",
    )
    manifest_parser.set_defaults(function=manifest)

    self_test_parser = subparsers.add_parser(
        "self-test", help="run deterministic release-evidence binding tests"
    )
    self_test_parser.set_defaults(function=run_self_test)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    return int(args.function(args))


if __name__ == "__main__":
    raise SystemExit(main())
