#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/_dev-helpers.sh
source "$SCRIPT_DIR/_dev-helpers.sh"
cex_load_env

export DATABASE_URL="$(cex_effective_database_url)"
export LEDGER_FAIL_FAST=true
export CEX_RUNTIME_PROFILE=trnm-economy
export CONSUMER_ENTRY_RUNTIME_PROFILE=production
export LEDGER_BASE_URL="${LEDGER_BASE_URL:-http://127.0.0.1:7002}"
export CONSUMER_ENTRY_BIND_ADDR="${CONSUMER_ENTRY_BIND_ADDR:-127.0.0.1:8090}"
export LEDGER_ADMIN_TOKEN="${LEDGER_ADMIN_TOKEN:-${IDENTITY_ADMIN_TOKEN:?IDENTITY_ADMIN_TOKEN is required}}"
export TRNM_VALUE_ENTITLEMENT_SIGNING_SECRET="${TRNM_VALUE_ENTITLEMENT_SIGNING_SECRET:-trnm-entitlement-signing-v1:$IDENTITY_ADMIN_TOKEN}"
export TRNM_PLAYER_SESSION_SIGNING_SECRET="${TRNM_PLAYER_SESSION_SIGNING_SECRET:-trnm-player-session-signing-v1:$IDENTITY_ADMIN_TOKEN}"
export TRNM_REQUIRE_PLAYER_SESSION=true
export TRNM_ALLOW_SYSTEM_ECONOMY_OPERATIONS=true
export CONSUMER_ENTRY_LEDGER_ADMIN_TOKEN="$LEDGER_ADMIN_TOKEN"
export CONSUMER_ENTRY_INGRESS_TOKEN="${CONSUMER_ENTRY_INGRESS_TOKEN:-$IDENTITY_ADMIN_TOKEN}"
export CONSUMER_ENTRY_SESSION_AUTH_SECRET="${CONSUMER_ENTRY_SESSION_AUTH_SECRET:-$IDENTITY_ADMIN_TOKEN}"
export CONSUMER_ENTRY_SESSION_AUTH_ALLOWED_ISSUERS="${CONSUMER_ENTRY_SESSION_AUTH_ALLOWED_ISSUERS:-trnm-native-client}"
export CONSUMER_ENTRY_SESSION_AUTH_EXPECTED_AUDIENCE="${CONSUMER_ENTRY_SESSION_AUTH_EXPECTED_AUDIENCE:-consumer-entry-api}"
export CONSUMER_ENTRY_REQUIRE_SESSION_AUTH=true
export CONSUMER_ENTRY_REQUIRE_IDENTITY_BINDING=true
export CEX_GATEWAY_API_KEY="${CEX_GATEWAY_API_KEY:-trnm-economy-local-production-key}"
export CONSUMER_ENTRY_LEAGUE_WEB_SESSION_SECRET="${CONSUMER_ENTRY_LEAGUE_WEB_SESSION_SECRET:-$IDENTITY_ADMIN_TOKEN}"
export CONSUMER_ENTRY_IDENTITY_BINDINGS_PATH="$CEX_PROJECT_ROOT/deploy/trnm-economy/identity-bindings.json"
export CONSUMER_ENTRY_IDENTITY_REGISTRY_PATH="$CEX_PROJECT_ROOT/deploy/trnm-economy/identity-registry.json"
export CONSUMER_ENTRY_IDENTITY_BINDING_APPROVED_REVISIONS_PATH="$CEX_PROJECT_ROOT/deploy/trnm-economy/identity-approved-revisions.json"
export CONSUMER_ENTRY_IDENTITY_BINDING_AUDIT_LOG_PATH="$CEX_PROJECT_ROOT/run/trnm-economy/identity-audit.jsonl"
export CONSUMER_ENTRY_IDENTITY_BINDING_RELOAD_REQUIRE_REVISION=true
export CONSUMER_ENTRY_IDENTITY_BINDING_RELOAD_REQUIRE_APPROVED_REVISION=true
export CONSUMER_ENTRY_IDENTITY_BINDING_RELOAD_REQUIRE_ACTOR=true
export CONSUMER_ENTRY_IDENTITY_BINDING_RELOAD_ALLOWED_ACTORS=cex-trnm-economy-service
export CONSUMER_ENTRY_REPLAY_STORE_PATH="$CEX_PROJECT_ROOT/run/trnm-economy/replay.json"
export CONSUMER_ENTRY_RATE_LIMIT_STORE_PATH="$CEX_PROJECT_ROOT/run/trnm-economy/rate-limit.json"
export CONSUMER_ENTRY_LEAGUE_STATE_PATH="$CEX_PROJECT_ROOT/run/trnm-economy/league-projection.json"
export CONSUMER_ENTRY_LEAGUE_NORMALIZED_DATABASE_URL="$DATABASE_URL"
export CONSUMER_ENTRY_LEAGUE_NORMALIZED_DUAL_WRITE_ENABLED=false
export CONSUMER_ENTRY_LEAGUE_NORMALIZED_READ_SWITCH_ENABLED=false
export CONSUMER_ENTRY_LEAGUE_NORMALIZED_FINAL_CUTOVER_ENABLED=false

mkdir -p "$CEX_PROJECT_ROOT/run/trnm-economy"
touch "$CONSUMER_ENTRY_IDENTITY_BINDING_AUDIT_LOG_PATH"
chmod 700 "$CEX_PROJECT_ROOT/run/trnm-economy"
chmod 600 "$CONSUMER_ENTRY_IDENTITY_BINDING_AUDIT_LOG_PATH"

cex_wait_postgres 60 1

case "${1:-}" in
  ledger)
    exec "$CEX_PROJECT_ROOT/target/release/ledger-service"
    ;;
  consumer)
    for _ in $(seq 1 60); do
      if curl -fsS "$LEDGER_BASE_URL/v1/trnm/economy/readiness" >/dev/null 2>&1; then
        exec "$CEX_PROJECT_ROOT/target/release/consumer-entry-api"
      fi
      sleep 1
    done
    echo "persistent ledger did not become ready" >&2
    exit 1
    ;;
  *)
    echo "usage: $0 <ledger|consumer>" >&2
    exit 64
    ;;
esac
